### ISSUE TITLE
AgentwithConverter cannot be used in WCCI environment

### ISSUE THREAD

**Issue by djmax008** [rte-france/Grid2Op#103]
## Environment
 - Grid2op version: `0.9.3`
 - System: `ubuntu16.04`
 - Additional system information

## Bug description
I followed the example in baseline and built up an agent as "class MyAgent(AgentWithConverter):". It works fine in the baseline for train and evaluation.
But when I make it as a submission and run "check_your_submission.py", it gives me an error "AttributeError: 'ActionSpace_l2rpn_wcci_2020' object has no attribute 'convert_obs'".

Myagent inherits the AgentwithConverter.
It shows me
'''
File "/venv_grid2op/lib/python3.6/site-packages/grid2op/Runner/Runner.py", line 647, in _run_one_episode
act = agent.act(obs, reward, done)
File "/venv_grid2op/lib/python3.6/site-packages/grid2op/Agent/AgentWithConverter.py", line 206, in act
transformed_observation = self.convert_obs(observation)
File "/venv_grid2op/lib/python3.6/site-packages/grid2op/Agent/AgentWithConverter.py", line 165, in convert_obs
return self.action_space.convert_obs(observation)
AttributeError: 'ActionSpace_l2rpn_wcci_2020' object has no attribute 'convert_obs'
'''

## How to reproduce
Create a submission with DoubleDuelingDQN baseline

**Comment by BDonnot** [comment]
Hello,

I'll be investigating on this issue as soon as i can.
One quick fix would be to define yourself the method "convert_obs" that you want your agent to use. 

Also can you provide with more information on how you build your agent ?

Benjamin

**Comment by djmax008** [comment]
Dear Benjamin,
I found the problem that I forgot to initialize the AgentwithConverter. Now it is working fine.
Thanks for your help!
Best,
