### ISSUE TITLE
Provide dataset in other ways

### ISSUE THREAD

**Issue by ritou11** [rte-france/Grid2Op#104]
The download of `l2rpn_wcci_2020.tar.bz2` and other datasets are extremely slow here. Also the connection is unstable and make it impossible for me to get the dataset.
Can you please provide them in other ways kindly (e.g., dropbox, google drive, one drive) and read the file in the program?

**Comment by BDonnot** [comment]
Hello,

The problem has been fixed. Unfortunately, to my knowledge it's not possible to make a simple `get` request from the list of clouds you listed above. 

But if you have a solution, we'll be happy to know how to do it

Benjamin

**Comment by ritou11** [comment]
Hi Benjamin,
Thanks for the quick fix.
However, now it's almost impossible for me to get it......
```
l2rpn_wcci_2020.tar.bz2:   0%|                   | 57.3k/4.55G [00:12<441:18:24, 2.86kB/s]
```
If you could upload the bz2 file on those drives, then we may download it manually. After that, the program could read bz2 from a local path.

**Comment by BDonnot** [comment]
Hello again, 

I'm sorry to hear you are experiencing a such a disagreement. Indeed waiting for 441hours does not seem like a reasonable solution.

In our discord https://discord.gg/cYsYrPT, I put some instructions on how to dowload the data from a microsoft one drive, and then how to unzip it into the proper directory that grid2op will understand.
