### ISSUE TITLE
Environment Document for L2RPN Competition

### ISSUE THREAD

**Issue by djmax008** [rte-france/Grid2Op#107]
## Documentation issue description
Hi,
I think it is better to describe what environment class is used for WCCI Competition in detail.
For example the `actionClass`, `rewardClass` and `legalActClass` ect.
The description on CodaLab website is too simple.
If we made an environment using `env = grid2op.make("l2rpn_wcci_2020")`, we are not sure what are the default arguments and whether they are the same as the platform in Codalab.

## Suggested modifications
```
Documentation issues are low priority. 
Please provide your suggested modifications to increase processing speed.
Thanks for your understanding.
```
Add more explanations in Codalab website about what is the default the `actionClass`, `rewardClass` and `legalActClass` setting.

## Additional context
Add any other context here.

**Comment by BDonnot** [comment]
The score is extensively detailed in the competition documentation. And it's especially written than you are free to choose a'y reward you want. So I'd say the default `reward_class` is irrelevant. Extensive documentation is available at https://grid2op.readthedocs.io/en/latest/reward.html

`actionClass` is, as in all grid2op environment made of Topology And Dispatch action. But I agree it could be more clear. If you have any wording that would be perfect.

`LegalActClass` is... As always the checking of the parameters (for cool down on substations and lines) and the fact that you cannot act on more than 1 line and 1 substation at the same time. As usual. This part could be more explicit I agree. For this part, again don't hesitate the let us know if you have any suggestions.


Thanks

**Comment by djmax008** [comment]
I have thought about it for a while. Probably the best and simplest way is to specify each argument in the environment. For example, if `env = grid2op.make("l2rpn_wcci_2020")` can guarantee the `env` is exactly the same as it in CodaLab, then we are good. Otherwise, it is better to have `env = make('l2rpn_wcci_2020', param=params, action_class=TopologyAndDispatchAction, reward_class=L2RPNReward, backend=backend)`
One reason for doing so is because most of time we have to reduce the action space and record the index of useful actions. But if the sequential order of action has changed, then the training agent will not work during evaluating. Similar things happen to the reward definition. 

Thanks,

**Comment by BDonnot** [comment]
If your agent depends on the action space that strongly, i would recommend you to have a look in the different possibility offered by the IdToAct converter, especially the serialization / de serialization of it.

This is does not appear to be a problem related to grid2op. For me this is rather a problem of not saving / loading back your model properly. Model include the weights and also the actions you are using. If you model only store the weight there is nothing grid2op can do about it.

As for the parameters ans the `backend` and the `param`, you are free to use anything you want at training time. But at time test, consider it is  `env = grid2op.make("l2rpn_wcci_2020")`.
`reward_class` is what you want it to be. We extensively write about it on codalab, on the starting kit and on the official documentation.

>  if env = grid2op.make("l2rpn_wcci_2020") can guarantee the env is exactly the same as it in CodaLab, then we are good.

This is a guarantee if you use the same version, which is `grid2op==0.9.1.post1`:
 `env = grid2op.make("l2rpn_wcci_2020")` is exactly the same as it is in CodaLab.

So i think we are good and i'm closing this issue :-)
