### ISSUE TITLE
Distinguish score and reward files

### ISSUE THREAD

**Issue by marota** [rte-france/Grid2Op#11]
Currently there is only one common .py script that is used to specify either the reward or the score.
What we are interested in when analyzing an agent, is to analyze the score of this agent. But when training the agent, we must give him a reward from which he should learn from. So we cannot define and compute the score currently when it is training.
To analyze the agent performance when he is training, it would be good to be able to compute the score at the same time. One possible solution is to explicitly separate the script .py file of score and reward.

**Comment by BDonnot** [comment]
I added (finally) the possibility to add different reward when creating an environment.

It can be done the following way:
```python
import grid2op
from grid2op.Reward import FlatReward, EconomicReward
env = grid2op.make(other_rewards={"score": FlatReward, "other_interesting_reward": EconomicReward})
```
And, after each call to "step" the "info" argument will contain the assessment of the given reward made by the environment:
```python
>>> act = env.action_space()
>>> obs, reward, done, info = env.step(act)
>>> info["rewards"]
{'score': 1, 'other_interesting_reward': 26618.593314812057} 
>>> obs, reward, done, info = env.step(act)
>>> info["rewards"]
{'score': 1, 'other_interesting_reward': 26469.417511663305}
```

A reward, used to train an agent is still required, and will be sent back to the agent as defined by the gym framework.

If other things need to be checked (other reward) or a score (in case of a competition) it can be done through the "other_rewards" argument.
