### ISSUE TITLE
Cannot run notebook of starting_kit_1

### ISSUE THREAD

**Issue by zenghsh3** [rte-france/Grid2Op#112]
## Environment
 - Grid2op version: `0.9.3`
 - System: `ubuntu16.04`

## Bug description
![image](https://user-images.githubusercontent.com/5762635/84113782-ce6aaf00-aa5d-11ea-9e59-e13f9e24fd88.png)

## How to reproduce
Run 1_Power_Grid_101_notebook.ipynb of starting_kit_1

**Comment by Anmar001** [comment]
Don't use Plotting, change it to PlotMatplot.

from grid2op.PlotGrid import PlotMatplot
plot_helper = PlotMatplot(observation_space=environment.observation_space)

**Comment by zenghsh3** [comment]
Thank you very much. It fixed the error. Maybe you should also update the notebooks.

**Comment by BDonnot** [comment]
Hello :-)

Sorry for answering in such a long delay. I thought i did, but apparently not :-/
Notebooks are fixed for the next set of competitions, the one happening for the Neurips conference :-)

I am closing this issue as there are not reason to continue using these starting kits when new ones will be available when the next competition will begin.

Thanks for reporting this issue 

Benjamin
