### ISSUE TITLE
Add the ".multimix" file in the data/l2rpn_neurips_2020_track2 test environment.

### ISSUE THREAD

**Issue by BDonnot** [rte-france/Grid2Op#119]
## Is your feature request related to a problem? Please describe.
Yes, when attempt to do "test=true" on the provided dataset (data/l2rpn_neurips_2020_track2) it fails because a file is missing.

## Describe the solution you'd like
just add the .multimix file in the appropriate folder :-)

**Comment by Tezirg** [comment]
The file is present already: https://github.com/rte-france/Grid2Op/tree/master/grid2op/data/l2rpn_neurips_2020_track2

It seems we forgot to install it: https://github.com/rte-france/Grid2Op/blob/master/MANIFEST.in
We will include a fix for that in the next release

Using `pip3 install -e .` should solve your issue until then
