### ISSUE TITLE
Crash on load disconnection 

### ISSUE THREAD

**Issue by Tezirg** [rte-france/Grid2Op#125]
## Environment
 - Grid2op version: `1.1.1`
 - System: `ubuntu20`

## Bug description
Disconnecting a load causes the solver to crash

### Code snippet

```python
import grid2op

env = grid2op.make()
env.reset()

action = env.action_space({"set_bus": {"loads_id": [(1, -1)]}})
obs, reward, done, info = env.step(action)
print(done, info)
```

## Current output
Process crashes with error:
```
Segmentation fault (core dumped)
```

## Expected output
Should just game over
```
True, {"has_error": True, ..., exception: "Disconnected load"}
```

**Comment by BDonnot** [comment]
Hello,

The easiest short term "solution" is not to set to "-1" the buses of loads and generators. This would lead to a game over instantly anyway. Buses for loads and generators should be either 0 (you don't change anything) or 1 or 2. 

Another possible fix would be to try to use a different backend. Lightsim2grid is probably at the moment the easiest thing to try. It's available at https://github.com/BDonnot/lightsim2grid and it super easy to use once installed. 

We'll have a look at this issue and propose a better longer term solution. 

Benjamin

**Comment by Tezirg** [comment]
Update on this, with lightsim the behavior ignores the load disconnection without providing feedback to the user

```python
import grid2op
try:
    from lightsim2grid.LightSimBackend import LightSimBackend
    backend = LightSimBackend()
except:
    print ("Fall back on default PandaPowerBackend")
    from grid2op.Backend import PandaPowerBackend
    backend = PandaPowerBackend()

env = grid2op.make(backend=backend)
env.reset()

action = env.action_space({"set_bus": {"loads_id": [(1, -1)]}})
obs, reward, done, info = env.step(action)
print (obs.topo_vect)
print (done, info)
```
```
[ 1  1  1  1  1  1  1  1  1  1  1  1 -1  1  1  1  1  1  1  1  1  1  1  1
  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
  1  1  1  1  1  1  1  1]
False 
{
    'disc_lines': array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False]), 
    'is_illegal': False, 
    'is_ambiguous': False, 
    'is_dispatching_illegal': False, 
    'is_illegal_reco': False, 
    'opponent_attack_line': None,
    'opponent_attack_sub': None, 
    'opponent_attack_duration': 0, 
    'exception': [], 
    'rewards': {}
}

```
