### ISSUE TITLE
Allow different parameters between simulate and step

### ISSUE THREAD

**Issue by marota** [rte-france/Grid2Op#128]
## Is your feature request related to a problem? Please describe.
Simulate and step function can run on different backends. But it would be useful also if they could run with different parameters as well such  {"NO_OVERFLOW_DISCONNECTION": True} for simulate and  {"NO_OVERFLOW_DISCONNECTION": False} for step

## Describe alternatives you've considered
To do it today, you can use hidden variables

obs, r, d, i = env.step(..)
obs._obs_env.no_overflow_disconnection = True
obs.simulate(...)

## Additional context
This is needed today for the Expert4Grid agent for instance

**Comment by BDonnot** [comment]
This is a working example, that indeed we need to dig in:

```python3
import grid2op
from grid2op.Parameters import Parameters

env = grid2op.make()
# modify the parmeters for simulate
param = Parameters()
param.MAX_SUB_CHANGED = 9999
param.MAX_LINE_STATUS_CHANGED = 9999
env.observation_space.obs_env.parameters = param

# and you can simulate the impact of action modifying as many substation as you want, for example
act = env.action_space({"set_bus": {"lines_or_id": [(0,2), (10,2)]}})
# this action modfies both substation 0 and substation 8
sim_o, sim_r, sim_d, sim_info = obs.simulate(act)
print(sim_info["is_illegal"]) # prints "False" meaning the action is legal
```

**Comment by BDonnot** [comment]
A solution to this problem will be made in next version of grid2op (version 1.3.2). The new API will be:
```python
import grid2op
from grid2op.Parameters import Parameters

env = grid2op.make()
# modify the parmeters for simulate
param = Parameters()
param.MAX_SUB_CHANGED = 9999
param.MAX_LINE_STATUS_CHANGED = 9999
env.change_forecast_parameters(param)
obs = env.reset()

# and you can simulate the impact of action modifying as many substation as you want, for example
act = env.action_space({"set_bus": {"lines_or_id": [(0,2), (10,2)]}})
# this action modfies both substation 0 and substation 8
sim_o, sim_r, sim_d, sim_info = obs.simulate(act)
print(sim_info["is_illegal"]) # prints "False" meaning the action is legal
```

Be cerefull though, the behaviour of `param.FORECAST_DC` attributes will changed to be consistent with the adding of this function.
If you want to use a DC model in the forecast, you will now have to do:
```python
param = Parameters()
param.ENV_DC = True
env.change_forecast_parameters(param)
obs = env.reset()
``` 
instead of the __**now wrong**__
```python
param = Parameters()
param.FORECAST_DC = True
```
