### ISSUE TITLE
Hard overflow doesn't work in some case.

### ISSUE THREAD

**Issue by lujasone** [rte-france/Grid2Op#130]
## Environment
 - Grid2op version: `0.9.1-post1`
 - System: `windows`
 - Additional system information
l2rpn_wcci_2020

## Bug description
Hard overflow doesn't break the powerline at once. It works like soft overflow.

## How to reproduce
I train the model with DDDQN, and run evaluate.py with gif on. Please check the attached gif file.
![Scenario_april_004](https://user-images.githubusercontent.com/25893320/87853293-83d13200-c93b-11ea-975b-cb3da9ba5985.gif)
### Command line (windows batch file)

set DQN_NAME=dqn-X.0.0.x
set DQN_DATA=D:/data_grid2op/l2rpn_wcci_2020

python inspect_action_space.py --path_data %DQN_DATA%
python evaluate.py ^
    --data_dir %DQN_DATA% ^
    --load_file ./models/%DQN_NAME%.h5 ^
    --logs_dir ./logs-eval/%DQN_NAME% ^
    --nb_episode 10 ^
    --gif ^
    --verbose

### Code snippet

```python
import grid2op

... # Some code 
```

## Current output

```
The output of the code snippet above
It keep alive for 3 timestamps, same as soft overflow.

## Expected output
<!--Describe the output you desire-->
```
The expected output and/or expected behavior description
The hard overflow powerline (Rho >200%) should be disconnected at once based on policy.

**Comment by Tezirg** [comment]
Hello @lujasone, thank you for reporting this issue.

I am not sure how this could happen as this behavior is unit tested and hasn't been modified recently. I did not managed to reproduce. 
 - Does it also happens on the latest release of Grid2Op `1.1.1` ? 
 - Can you provide the scenario name ? 
 - Regarding the baseline, can you give the baseline package version and modifications you may have made to it ?

**Comment by BDonnot** [comment]
Hello,

I think we forgot to keep you updated on the matter. This is a problem of the wrong numbers we put in the configuration files (we put 200 meaning 20 000% by mistake) we will try to hotfix this as soon as possible :-)

**Comment by Tezirg** [comment]
Release `1.2.2 `includes a utility method to update invalid configurations files:

```python
import grid2op
grid2op.update_env()
```
