### ISSUE TITLE
Observation forecasts attributes & EpisodeData observations to include forecasts

### ISSUE THREAD

**Issue by Tezirg** [rte-france/Grid2Op#132]
## Is your feature request related to a problem? Please describe.
I would like to access the forecast via observation attributes
I would like to see the forecasts in the observations when loading from disk

## Describe the solution you'd like
Access forecasts values from observations directly:
```python
timestep=1
t1_load_pf = obs.load_p_f[timestep]
t1_load_qf = obs.load_q_f[timestep]
t1_prod_pf = obs.prod_p_f[timestep]
t1_prod_vf = obs.prod_v_f[timestep]
```
Have these serialized alongside observations attributes for EpisodeData:
[grid2op/Observation/CompleteObservation.py L.101](https://github.com/BDonnot/Grid2Op/blob/master/grid2op/Observation/CompleteObservation.py#L101)
```python
        self.attr_list_vect = [
            "year", "month", "day", "hour_of_day",
            "minute_of_hour", "day_of_week",
            "prod_p", "prod_q", "prod_v",
            "load_p", "load_q", "load_v",
            "p_or", "q_or", "v_or", "a_or",
            "p_ex", "q_ex", "v_ex", "a_ex",
            "rho",
            "line_status", "timestep_overflow",
            "topo_vect",
            "time_before_cooldown_line", "time_before_cooldown_sub",
            "time_next_maintenance", "duration_next_maintenance",
            "target_dispatch", "actual_dispatch",
            # Adding forecasts HERE
            "prod_p_f", "prod_v_f", "load_p_f", "load_q_f"
        ]
```

**Comment by BDonnot** [comment]
This is actually a good idea as it would allow easier manipulation of the forecasts.

However, one main problem is that it would break the backward compatibility of the agent's runner logs with this addition... 

A more subtle problem would also arise when the environment does not give forecast. Not considering the forecast as part of the observation makes it rather easy to switch from different chronics with / without them and to disable them from the environment for example if we don't need them. Here it would mean having big chunks of the observations set to 0 when forecast are deactivated or not available :-/
