### ISSUE TITLE
TypeError: sample() missing 1 required positional argument: 'space_prng'

### ISSUE THREAD

**Issue by Alwinator** [rte-france/Grid2Op#133]
grid2op/Action/SerializableActionSpace.py Line 89

Line 89: res.sample()

Needs to be replaced with: res.sample(self.space_prng)

**Comment by Alwinator** [comment]
@Tezirg I just tested it with the new commit and it works. Why did you reopen the issue?

**Comment by Tezirg** [comment]
> @Tezirg I just tested it with the new commit and it works. Why did you reopen the issue?

We close issues once they have been propagated to the main repo in a release. Right now the fix is still on branch, on the dev fork (awaiting review)

**Comment by Alwinator** [comment]
Okay, sounds good.

**Comment by steliospnnl** [comment]
I changed replaced line 89 and am still having the issue... Any ideas what I might be doing wrong?

**Comment by BDonnot** [comment]
@steliospnnl hello :-)
Can you provide with an example on the broken code please ? We will do a new grid2op version soon (we hope) that will fix all the bugs encountered as of today (and there are quite a lot) :-)
Thanks
