### ISSUE TITLE
Cascading Failure not well detected

### ISSUE THREAD

**Issue by marota** [rte-france/Grid2Op#143]
## Environment
 - Grid2op version: `1.2.0`
 - System: osx
 - Additional system information

## Bug description

An action leads to a cascading failure when played. More precisely, a line get disconnected and then some part of the grid is not connex anymore.
Info does not report that:
"{'disc_lines': array([False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False, False, False, False,
       False, False]), 'is_illegal': False, 'is_ambiguous': False, 'is_dispatching_illegal': False, 'is_illegal_reco': False, 'opponent_attack_line': None, 'opponent_attack_sub': None, 'opponent_attack_duration': 0, 'exception': [], 'rewards': {}}"

In addition to line 10, Two more lines get actually disconnected when looking at a_or:
array([100.05612 , 104.587364,  83.794426, 127.491264,  99.934044,
        53.22422 , 123.58554 ,        nan, 239.23209 , 614.0957  ,
         0.      , 180.84364 ,        nan,  74.35664 , 337.7738  ,
        99.533554,  46.24458 ,  58.005096, 863.24457 , 549.52826 ],
      dtype=float32)

### Command line

```bash
# command line used if any 
```

### Code snippet

```python
import grid2op
dataset = 'rte_case14_realistic'

env=make(dataset)

timestep=0
chronic_scenario=0
env.set_id(chronic_scenario)
env.reset()

sub_id=5
target_topology=[2, 1, 1, 1, 1, 2]     
action_def={"set_bus": {"substations_id": [(sub_id, target_topology)] } }
action=env.action_space(action_def)
osb,reward,done,info=env.step(action)
 
```

## Current output

```
{'disc_lines': array([False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False, False, False, False,
       False, False]), 'is_illegal': False, 'is_ambiguous': False, 'is_dispatching_illegal': False, 'is_illegal_reco': False, 'opponent_attack_line': None, 'opponent_attack_sub': None, 'opponent_attack_duration': 0, 'exception': [], 'rewards': {}}

```

## Expected output

```
"{'disc_lines': array([False, False, False, False, False, False, False, **True**, False,
       False,  True, False, **True**, False, False, False, False, False,
       False, False]), 'is_illegal': False, 'is_ambiguous': False, 'is_dispatching_illegal': False, 'is_illegal_reco': False, 'opponent_attack_line': None, 'opponent_attack_sub': None, 'opponent_attack_duration': 0, 'exception': [**"Non connex Grid" or "cascading failure"**], 'rewards': {}}"

```

**Comment by marota** [comment]
[CascadingFailureAction_notReported.pptx](https://github.com/rte-france/Grid2Op/files/5096437/CascadingFailureAction_notReported.pptx)
A file illustrating the case

**Comment by BDonnot** [comment]
Can you update to latest version please and let us know if the same behaviour is noted ?
Do you know if it happens only on default pandapower backend ?

Thanks :-)
