### ISSUE TITLE
Modifying observation object may lead to exception in the environment

### ISSUE THREAD

**Issue by AlexTo** [rte-france/Grid2Op#151]
In some rare cases, modifying the observation object may cause exception the next time we do `env.step(act)`

For example, the code below reproduces such "bug"

```
import grid2op
if __name__ == '__main__':
    env = grid2op.make("l2rpn_case14_sandbox")
    do_nothing = env.action_space({})
    s, r, done, info = env.step(do_nothing)
    setattr(s, "line_status", getattr(s, "line_status") / 1)  # do some weird things to the vector "line_status"
    _, _, _, _ = env.step(do_nothing)
    print("Exception above")
```

**Comment by BDonnot** [comment]
Hello :-)

Thanks for letting us know, we'll do our best. This is probably due to a shallow copy vs deep copy of a numpy array when the observation is created. 

I'll try to fix it in next release :-)

Benjamin
