### ISSUE TITLE
Pass Nones to BasePlot.plot_info gen_values argument

### ISSUE THREAD

**Issue by vinault** [rte-france/Grid2Op#155]
## Is your feature request related to a problem? Please describe.
When using BasePlot.plot_info, the behavior of the function with respect to line_values and gen_values seems inconsistent. lines_values will accept Nones while gen_values will not.

## Describe the solution you'd like
Passing Nones to either line_values or gen_values is a neat trick so selectively remove some information on the graph. See an example below where le line ids are only shown for some lines (e.g. the lines impacted by actions during an episode).
 
![image](https://user-images.githubusercontent.com/25577263/96932853-d46aa500-14bf-11eb-9309-988ea961d06d.png)

## Describe alternatives you've considered
An alternative to convey some information about the actions on the graph would be to use some differenciating colors (which is not yet possible I reckon) or adding some markers on different elements (lines, gens and subs).

**Comment by BDonnot** [comment]
Since grid2op 1.3.1 this is possible.

The following code is working:

```python
import grid2op
from grid2op.PlotGrid import PlotMatplot
env = grid2op.make()
plot_helper = PlotMatplot(env.observation_space)
fig = plot_helper.plot_info(gen_values=[None, None, 1, 2, 3, 4])
fig.show()
```
And this gives:
![grid_img](https://user-images.githubusercontent.com/9463182/99086063-4cad1d80-25c9-11eb-8c5e-df75073d06ab.png)

Note that as expected the generator 0 and 1 have no values associated to them.

**Comment by vinault** [comment]
Fantastic ! Thanks @BDonnot.
