### ISSUE TITLE
`actual_dispatch`  is not as expected.

### ISSUE THREAD

**Issue by zenghsh3** [rte-france/Grid2Op#156]
## Environment
 - Grid2op version: `1.2.2`
 - System: `ubuntu16.04`

### Code snippet
```python
import grid2op
import lightsim2grid
assert grid2op.__version__ == "1.2.2"
assert lightsim2grid.__version__ == "0.2.4"

from lightsim2grid.LightSimBackend import LightSimBackend
import numpy as np


backend = LightSimBackend()
env = grid2op.make("l2rpn_neurips_2020_track1_small", backend=backend)

seed = 3
np.random.seed(seed)
env.seed(seed)

env.set_id(np.random.randint(100000))
_ = env.reset()

MAX_TIMESTEP = 288 * 7
max_day = (env.chronics_handler.max_timestep() - MAX_TIMESTEP) // 288
start_timestep = np.random.randint(max_day) * 288 - 1 # start at 00:00
if start_timestep > 0:
    env.fast_forward_chronics(start_timestep)

obs = env.get_obs()


pos_act = env.action_space({"redispatch": [(2,+0.8), (3, +4.9)]})
neg_act = env.action_space({"redispatch": [(2,-0.8), (3, -4.9)]})

obs, reward, done, info = env.step(pos_act)
obs, reward, done, info = env.step(neg_act)
obs, reward, done, info = env.step(env.action_space({}))
print("actual_dispatch: ", obs.actual_dispatch)
print("target_dispatch: ", obs.target_dispatch)
```

## Current output
actual_dispatch:  [-0.03796365  0.         -0.03988035 -0.29241502  0.465155    0.
  0.          0.          0.          0.         -0.07849512  0.
  0.         -0.07849512  0.          0.         -0.12057994  0.
  0.         -0.07849512  0.5411701  -0.28000093]
target_dispatch:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

## Expected output
actual_dispatch:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
target_dispatch:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

**Comment by BDonnot** [comment]
Hello,

This is a perfectly normal behaviour. Let me try to explain with a concrete example:

```python
import grid2op
from grid2op.Parameters import  Parameters
import numpy as np
param = Parameters()
param.NO_OVERFLOW_DISCONNECTION = True  # not be bothered with "game over"
env = grid2op.make("l2rpn_neurips_2020_track1_small", param=param)

seed = 3
np.random.seed(seed)
env.seed(seed)

env.set_id(np.random.randint(100000))
_ = env.reset()

MAX_TIMESTEP = 288 * 7
max_day = (env.chronics_handler.max_timestep() - MAX_TIMESTEP) // 288
start_timestep = np.random.randint(max_day) * 288 - 1  # start at 00:00
if start_timestep > 0:
    env.fast_forward_chronics(start_timestep)

obs = env.get_obs()
gen_id = 20
print("Maximum ramp down for generator 20 {}".format(-obs.gen_max_ramp_down[gen_id]))
pos_act = env.action_space({"redispatch": [(2, +0.8), (3, +4.9)]})
neg_act = env.action_space({"redispatch": [(2, -0.8), (3, -4.9)]})

obs, reward, done, info = env.step(pos_act)
print("\tproduction absorbed for generator 20 (after first action) {}".format(obs.actual_dispatch[gen_id]))
obs, reward, done, info = env.step(neg_act)
print("\tproduction absorbed for generator 20 (after second action) {}".format(obs.actual_dispatch[gen_id]))
prev_obs = obs
for i in range(5):
    obs, reward, done, info = env.step(env.action_space({}))
    print("\tproduction absorbed for generator 20  after \"do nothing\" action {}: {}".format(i, obs.actual_dispatch[gen_id]))
    print("\tdelta prod_p after \"do nothing\" action {}: {}".format(i, obs.prod_p[gen_id] - prev_obs.prod_p[gen_id]))
    prev_obs = obs
print("actual_dispatch: ", obs.actual_dispatch[gen_id])
print("target_dispatch: ", obs.target_dispatch[gen_id])
```
When you do the first dispatch, the generator 20 absorbs 0.08 MW.
Then you do the other action, and this generator produces 0.63 MW more (`obs.actual_dispatch[gen_id] == 0.63`)
So after the second action, it has not been set back to its original value (which would be 0.0)

And then, as in the data, its production decreases almost of its ramp. Its ramp is -8.5 MW / time step, and as you can see, in the following 5 steps (when doing nothing) is always around `-8.49` (execute the code and look at the print) this means that it's not physically possible to decrease production of generator 20 more than what it does.
And the "what it does" is not enough to absorb the 0.63MW "it produces more".
In this case, it takes 5 steps to "cancel" the +0.63MW, as you can see, at then end the "actual dispatch" is almost 0 (the algorithm is not run if the differences are less than 0.1MW I think)

**Comment by zenghsh3** [comment]
Hi, Thanks for your quick reply. So after several steps, the env will be restored to the original state (but there are precision issues).

**Comment by BDonnot** [comment]
Generators data in the chronic files are stored with a precision of 1e-1, so yes the environment does not really try to get to 0.000 for all generators for all steps, this would be a waste of computation resources.
This explains why, after 5 time steps you obtain a vector looking like:
```python
>>> actual_dispatch =  [-0.0041556   0.         -0.00415561 -0.02694124  0.00515547  0.
  0.          0.          0.          0.         -0.00682103  0.
  0.         -0.00682103  0.          0.         -0.00653452  0.
  0.         -0.00682103  0.08117009 -0.02407568]
```
But before this 5th do nothing step, then it's not at all "precision issue", it's physical limits. The environment would like to to get rid of this +0.63MW on generator 20, but it cannot because generator 20 is decreasing of its maximum value (8.5MW per time step) already (as you can see in the prints *eg* `delta prod_p after "do nothing" action 2: -8.489997863769531` )

**Comment by zenghsh3** [comment]
I see! thanks for your detailed explanation.👍
