### ISSUE TITLE
Inaccuracy in documentation about Observation

### ISSUE THREAD

**Issue by AlexTo** [rte-france/Grid2Op#158]
[This link](https://grid2op.readthedocs.io/en/latest/observation.html#grid2op.Observation.BaseObservation.year) mentions that `month` is 0-based indexing but looks like it is not because according to the following code, April is 4, not 3 ?

![image](https://user-images.githubusercontent.com/296212/97158901-2d8f4d00-17ce-11eb-9236-9e52108de662.png)

Please confirm other attributes as well such as day_of_week

**Comment by BDonnot** [comment]
Hello,

The dates and times, and all the other calendar data are computed with the associated attributes of the "datatime.datetime" object.

So indeed it's labelled to be "human friendly":
- month are between 1 and 12
- days are between 1 and 31 (max depends on the month)
- hour_of_day is between 0 and 23
- minute_of_hour is between 0 and 59
- day_of_week is between 0 and 6

Can you point me out were you spotted this mistake ? I don't see it on the documentation.

**Comment by AlexTo** [comment]
Hi Benjamin

In the link from my previous post, it says "January = 0"

![image](https://user-images.githubusercontent.com/296212/99127021-6d25b800-265b-11eb-9d88-da96639d8ea9.png)

**Comment by BDonnot** [comment]
I fixed that, the documentation should be pushed in the next few minutes.

Thanks for noticing
