### ISSUE TITLE
Improve Gym integration

### ISSUE THREAD

**Issue by BDonnot** [rte-france/Grid2Op#16]
I think it's now time to add a full gym integration (and dependency) for the environment (that is almost done already) but also for observation and action spaces.

This would mean introducing the gym framework as a dependency and check for license first.

This would also make some use of other RL methods easier.

**Comment by BDonnot** [comment]
For information, to get a "gym" observation space, you can get the following:
```python
import grid2op
from gym import spaces
env = grid2op.make(...)
gym_observation_space = spaces.Dict({attr_nm: spaces.Box(low=-np.inf, high=np.inf, shape=(sh,), dtype=dt) for attr_nm, sh, dt in zip(env.observation_space._empty_obs.attr_list_vect, env.observation_space.shape, env.observation_space.dtype)})
```

**Comment by Kronos9247** [comment]
Please include gym in the competition container

**Comment by BDonnot** [comment]
@Kronos9247 Hello :-)

Gym has been added in the competition container (in version 0.17.2).

Also you might want to check out the documentation at https://grid2op.readthedocs.io/en/latest/#compatibility-with-openai-gym that presents the classes we added for improving compatibility with Gym :-)

Don't hesitate to let us know if you need anything 

Benjamin

**Comment by BDonnot** [comment]
As of grid2op 1.3.1 the module "grid2op.gym_compat" has been introduced.

```python
import grid2op
from grid2op.gym_compat import GymEnv

env_name = ...
env = grid2op.make(env_name)
gym_env = GymEnv(env)  # is a gym environment properly inheriting from gym.Env !
```

There are lots of possibilities to modify the encoding of the action space or the observation. Do not hesitate to check out https://grid2op.readthedocs.io/en/latest/gym.html for more information
