### ISSUE TITLE
Update the Grid2Viz command in Notebook "8_PlottingCapabilities.ipynb"

### ISSUE THREAD

**Issue by Mleyliabadi** [rte-france/Grid2Op#162]
## Documentation issue description
In notebook "8_PlottingCapabilities.ipynb" [section V-3 ) usage], the command "grid2viz.main --path=$path_agents" is out of date.

## Suggested modifications
To be replaced with "grid2viz.main --agents_path=$path_agents"

**Comment by BDonnot** [comment]
The issue has been fixed now.

Thanks for noticing
