### ISSUE TITLE
Pass environment config parameters when loading Grid2op logs - plot observation use case

### ISSUE THREAD

**Issue by marota** [rte-france/Grid2Op#168]
## Is your feature request related to a problem? Please describe.
Currently when loading logs, the observation space is of the type _SerializableObservationSpace_
https://github.com/rte-france/Grid2Op/blob/bf0c1db1acb8ee4c1002cbb862728ee29168807e/grid2op/Episode/EpisodeReplay.py#L110
https://github.com/rte-france/Grid2Op/blob/bf0c1db1acb8ee4c1002cbb862728ee29168807e/grid2op/Episode/EpisodeData.py#L375
https://github.com/rte-france/Grid2Op/blob/bf0c1db1acb8ee4c1002cbb862728ee29168807e/grid2op/Episode/EpisodeData.py#L425
https://github.com/rte-france/Grid2Op/blob/bf0c1db1acb8ee4c1002cbb862728ee29168807e/grid2op/Observation/SerializableObservationSpace.py#L46
It does not take as attribute environment parameters as the _ObservationSpace_ class. 

I wanted to be able to identify from an observation if some asset was in its first timestep of cooldown (to infer for instance that an action just occured there), and I needed to compare the cooldown value in the observation from the max cooldown in the environment parameters. This information could then be displayed on a grid plot with existing grid2op plotting utilities.

## Describe the solution you'd like
Give _SerializableObservationSpace_ an attribute for env parameters that can be found in logs

## Describe alternatives you've considered
Make this observation space an  _ObservationSpace_ class object, but it might require to load an environment in addition which is not necessarily needed

## Additional context
Add any other context about the feature request here.

**Comment by BDonnot** [comment]
Parameters are not part of the action_space or the observation_space. So it would be super weird to have them part of them when we de serialize them.

However, it's perfectly fine to reload them from the logs without any issue as they are stored there and can be reloaded without any issue.

For example:

```python
import os
from grid2op.Episode import EpisodeData
from grid2op.Parameters import Parameters
path_logs = ...

# list all the episode stored there
li_episode = EpisodeData.list_episode(path_logs)

# study for example the first episode:
path_episode, episode = li_episode[0]
param_of_the_episode = Parameters(parameters_path=os.path.join(path_episode, episode, "_parameters.json"))
```
