### ISSUE TITLE
Inconsistency in Runner detailed outputs when game over with other reward

### ISSUE THREAD

**Issue by NMegel** [rte-france/Grid2Op#170]
This happens when using a grid2op Runner in detailed mode (available in a post-release version, after pull-request for Oracle needs https://github.com/BDonnot/Grid2Op/pull/122)
When a game over occurs during the simulation, the convention between result.rewards and result.other_rewards are not the same: one gets NaN, one gets its array shortened to the divergence timestep

In order to reproduce, see the code and grid in the zipped folder attached. You'll see that results.rewards has length of 50 whereas result.other_rewards has length 45

[inconsistency_reproduction_grid2opRunner.zip](https://github.com/rte-france/Grid2Op/files/5994597/inconsistency_reproduction_grid2opRunner.zip)

**Comment by BDonnot** [comment]
Hello,

After a relatively quick look, it appears the bug should be either in this new feature so Mario might know the most about it, or about the "EpisodeData" class, which again was developped by Mario / Nicolas.

I thing the best would be to get in touch with them to fix it in grid2op rather that to put son glue in dependant code.

Benjamin

**Comment by BDonnot** [comment]
I think this has been fixed and the changes are not ported in the main package.
