### ISSUE TITLE
No any improvement during training via stable baseline 3 framework

### ISSUE THREAD

**Issue by hlhsu** [rte-france/Grid2Op#191]
## Environment
 - Grid2op version: `1.5.0`
 - System: ubuntu20.04, ...`
 - Additional system information

## Bug description
I follow the 11_IntegrationWithExistingRLFrameworks.ipynb to use stable baseline 3 for training "rte_case14_realistic". I can successfully ran the codes while it did not show any improvement during training. The episode reward or the survival time in the same chronic is always the same.

## How to reproduce
I even tried to only train for a single chronic while the result is still the same. I am wondering if you can provide any non-optimal parameters for the training. I actually tuned multiple hyperparameters in PPO (stable baselines 3), but it shows the same reward.

## Expected output
I expect that the reward will increase during training and converge while currently, it is just a horizontal line.

**Comment by BDonnot** [comment]
Hello,

As we mentionned in the notebook, these notebooks are just here to glue some piece of code together that allow the use of some RL packages with grid2op.

Indeed, we did not carry out any fine tuning of hyper parameters of anything like that. So i'm not sure this is a bug of grid2op.

Compared to simplest environment (eg. cartpole) L2RPN are much more complicated, with observations being "non standard data" (graph) and actions being most of the time action to change this graph.

Also, i could not recommend to use the "rte_case14_realistic" at all (see https://grid2op.readthedocs.io/en/latest/available_envs.html#list-of-available-environment for a list and a short descriptions of the available environments). And actually a warning is issue that says exactly that:
> This environment is not intended for training agents

Some advice i can give you to help you debug:
- carefully read the tips and tricks provided by stable baseline. In my opinion they are really usefull: https://stable-baselines3.readthedocs.io/en/master/guide/rl_tips.html
-  use another environment, i don't believe it will hurt
- try to use more simple action, for example only redispatching, curtailment, and action on storage unit, if any storage units on the grid (basically just use `act.redispatch`, `act.curtail` and `act.storage_p` and not `act.set_bus` or `act.change_bus` in first steps)
- have a look at the method that worked on previous environment, some are in l2rpn-baselines (https://github.com/rte-france/l2rpn-baselines) repo, some are listed on our discord (not integrated yet into l2rpn baselines). Most of winning approach are described with a video on our website (for example https://l2rpn.chalearn.org/competitions#h.obo9btx412m5)
- try to modify the parameters of the environment (the key-word arguments "param" when you create it with the "make" function by for example turning off the disconnection of powerline on overload [see bellow for an example]). It might help you to choose an appropriate NN architecture
- try to use another algorithm than PPO
- try to improve the exploration. Exploration is key here as the video from the winner of WCCI 2020  team explains really well (the "do nothing" is a sub optimal policy, but if you deviate slightly from it at the beginning, your agent will do worst than "do nothing")
- use the "lightsim2grid" backend for grid2op to be ~10x faster (see https://github.com/BDonnot/lightsim2grid) so to be able to train for more steps without waiting longer
- etc. etc.

As promised, the code for customizing the environment to make it "easier": (in that case the environment will not disconnect powerline on overflow)

```python
import grid2op
from grid2op.Parameters import Parameters
param = Parameters()
param.NO_OVERFLOW_DISCONNECTION = True
env = grid2op.make("l2rpn_case14_sandbox", param=param)
```

And if you want to change the backend (for lightsim2grid, once installed):

```python
import grid2op
from lightsim2grid import LightSimBackend
env = grid2op.make("l2rpn_case14_sandbox", backend=LightSimBackend())
```

Of course you can combine everything "tips" above :-)

**Comment by hlhsu** [comment]
Hello, thank you for so detailed descriptions. Just for double-checking, you mentioned that rte_case14_realistic is not recommended. Then do you mean that if I really want to train agents in 14 bus, l2rpn_case14_sandbox should be the best choice for me. Or if you have any better option in the link you just provided. Thank you!

**Comment by BDonnot** [comment]
Hi,

Yes i think this one should be the best one indeed. At least the `l2rpn_case14_sandbox` comes with lots of data :-)

And the data has been validated to be representative of something (we spent some time to calibrate it properly)

And you're welcome :-)

**Comment by hlhsu** [comment]
Really appreciated!
