### ISSUE TITLE
Different starting timestep for runner computation

### ISSUE THREAD

**Issue by mjothy** [rte-france/Grid2Op#210]
## Is your feature request related to a problem? Please describe.

This feature is needed for using the Runner multithreading in Oracle4Grid : 
https://github.com/marota/Oracle4Grid/issues/33

See https://github.com/marota/Oracle4Grid/blob/main/oracle4grid/core/reward_computation/attacks_multiverse.py

Specifically the `compute_one_multiverse()` function is a re-implementation of the Runner with a fast_forward_chronicles() to start at a different point.

## Describe the solution you'd like

The runner could have an additional argument "start_timestep == 0" which would do a fast_forward_chronicles().

Warning, the logic for initializing the EpisodeData arrays, and other return values will need to take into account this start_timestep

In the oracle, we have a "begin" and "end" argument, but for Grid2op, "begin" and "max_iter" could do the same thing.

      agent_class = OneChangeThenOnlyReconnect.gen_next(action.grid2op_action)
      runner = Runner(**params_for_runner, agentClass=agent_class)
      #Compute 5 timesteps from the 10th one
      res = runner.run(nb_episode=1,
                                nb_process=1,
                                start_timestep= 10
                                max_iter=5,
                                add_detailed_output=True,
                                env_seeds=env_seed,#ENV_SEEDS,
                                agent_seeds=agent_seed)

## Describe alternatives you've considered

We implemented our own mini-runner, but hit an issue for Parrallel computing, since the Runner does a few complex things to make it work.

**Comment by mjothy** [comment]
Added info : 

https://github.com/marota/Oracle4Grid/blob/main/oracle4grid/core/reward_computation/attacks_multiverse.py

in the oracle, we tried to see if we could parralelise the `compute_all_multiverses` function, but the presence of the env makes it very hard (something the Runner already solved with the inner "copy" of the env), since it's not picke able.

This feature seems like it would benefit other people that might want to only focus on a specific window of timesteps, without running the whole thing.

**Comment by BDonnot** [comment]
You will be able to use the "FromNPY" chronics class for such purpose.

Note this is a "use at your own risk" kind of things (you can do anything you want, only basic tests are made, results might be incorrect without warnings if you are not carefull)
