### ISSUE TITLE
Allow for grid elements that are not controllable but part of the power grid

### ISSUE THREAD

**Issue by janviebahn** [rte-france/Grid2Op#217]
## Is your feature request related to a problem? Please describe.
My grid.json (a pandapower grid) includes elements like sgen or trafo3w. These elements are currently not modelled in grid2op. When initializing the grid (using grid2op.make) I do NOT get an error in the Pandapower backend but in GridObjects.py (line 1574)

BackendError: Grid2OpException BackendError "There are 245 bus with 0 element connected to it." 

The reason is that these extra elements are not included in sub_info, and that some busbars only connect to these kind of elements.

Note that I'm using Grid2Op v1.5.0.

## Describe the solution you'd like
It would be great if all power system elements in a pandapower grid model are accepted by grid2op. These are, of course, important for the load flow calculations.
I'm not asking (yet) that these elements need to be controllable by the agent. They do not need to appear in the action space.

**Comment by BDonnot** [comment]
Hello,

In order to help you solve your issue, an access to a grid (maybe not the grid you're using) that has the same problem you encounter would be much appreciated. 

It is really hard (if not impossible) to solve a problem without being able to reproduce it.

**Comment by BDonnot** [comment]
This causes this kind of bug:
![image](https://user-images.githubusercontent.com/9463182/120646382-c4656b80-c479-11eb-99e1-1acfe5fe2097.png)

And can be solved (ugly manner) by deactivating the check.:
> Just comment the two lines 1573 and 1574 in the file in /home/cdsw/.local/lib/python3.6/site-packages/grid2op/grid2op/Space/GridObjects.py

**Comment by janviebahn** [comment]
> Hello,
> 
> In order to help you solve your issue, an access to a grid (maybe not the grid you're using) that has the same problem you encounter would be much appreciated.
> 
> It is really hard (if not impossible) to solve a problem without being able to reproduce it.

The problem can be easily reproduced. Please find attached the grid_modified.json

In order to create grid_modified.json I started out from rte_case5_example/grid.json and applied the following code

import pandapower as pp

net = pp.from_json("grid.json")

pp.create_bus(net, name = "substation_6", vn_kv = 20)
pp.create_bus(net, name = "substation_7", vn_kv = 10)
pp.create_transformer3w(net, hv_bus = 4, mv_bus = 5, lv_bus = 6, name = "trafo3w", std_type = "63/25/38 MVA 110/20/10 kV")
pp.create_sgen(net, 6, p_mw = -10)
pp.create_shunt(net, 5, 10)

pp.to_json(net, "grid_modified.json")

**Comment by BDonnot** [comment]
Issue is fixed, new changes can be obtained by installing the dev version of grid2op:

`pip install git+git://github.com/rte-france/grid2op.git@dev_1.6.0`

**Comment by BDonnot** [comment]
Fixed and merged in version 1.6.0, now available on pypi
