### ISSUE TITLE
ScoreL2RPN2020 used reco_powerline for score reference of 80 and not do nothing

### ISSUE THREAD

**Issue by marota** [rte-france/Grid2Op#228]
## Environment
 - Grid2op version: `1.5.2`
 - System: ` osx ...`
 - Additional system information

## Bug description
In 2020 L2RPN competitions, the score rescaled used the reco_powerline agent to set base score of 80 and 100 (see for instance https://github.com/marota/Grid2Op_EnvironmentDesign/blob/master/competition_codalab/score_config.py).
 rather than the do-nothing which is currently called here https://github.com/rte-france/Grid2Op/blob/097b756d5ac6a96f2eb17446b5ce749c6555452a/grid2op/utils/l2rpn_2020_scores.py#L93

## How to reproduce

When running ScoreL2RPN2020 with reco_powerline with NO_OVERFLOW_DISCONNECTION": True we should have a score of 80 on a given episode.

### Command line

```bash
# command line used if any 
```

### Code snippet

```python
import grid2op
from grid2op.Reward import RedispReward
from grid2op.utils import ScoreL2RPN2020

from grid2op.Parameters import Parameters
from grid2op.Agent import RecoPowerlineAgent

# create the backend
try:
    from lightsim2grid.LightSimBackend import LightSimBackend
    backend = LightSimBackend()
except:
    from grid2op.Backend import PandaPowerBackend
    backend = PandaPowerBackend()
    
reward = RedispReward

#############
input_dir_neurips="YourPath/input_data_val"
####

param = Parameters()
param.init_from_dict({"NO_OVERFLOW_DISCONNECTION": True})
real_env = grid2op.make(input_dir_neurips,
                        reward_class=reward,backend=backend,param=param)

###computing L2RPNScore
nb_episode=1
my_score = ScoreL2RPN2020(real_env,
                          nb_scenario=nb_episode,
                          env_seeds=[0],
                          agent_seeds=[0]
                          )

my_agent = RecoPowerlineAgent(real_env.action_space)
final_score_reco=my_score.get(my_agent)
assert(final_score_reco[0][0]==80)
```

## Current output

```
The output of the code snippet above
```

## Expected output

```
The expected output and/or expected behavior description
```

**Comment by BDonnot** [comment]
Fixed and merged in version 1.6.0, now available on pypi
