### ISSUE TITLE
Best_time and window_size are inverted at AlarmReward creation

### ISSUE THREAD

**Issue by marota** [rte-france/Grid2Op#229]
## Environment
 - Grid2op version: `1.6.0`
 - System: `osx`
 - Additional system information

## Bug description
Best_time and window_size are inverted at AlarmReward creation

## How to reproduce

see here:
https://github.com/rte-france/Grid2Op/blob/e19cb7590d3fcd697972aaabfb2a3bcff4b3f0e1/grid2op/Reward/AlarmReward.py#L71

**Comment by marota** [comment]
A suggestion for improvement here: rather than -1, use self.reward_min ?

https://github.com/rte-france/Grid2Op/blob/e19cb7590d3fcd697972aaabfb2a3bcff4b3f0e1/grid2op/Reward/AlarmReward.py#L154

 => best_score, is_alarm_used = self.reward_min, False

**Comment by BDonnot** [comment]
I don't get it, this reward returns a score between -1 and 1 so -1 and `reward_min` are the same, no ?

**Comment by BDonnot** [comment]
Fixed and merged in version 1.6.0, now available on pypi
