### ISSUE TITLE
Installed packages for the ICAPS 2021 competition

### ISSUE THREAD

**Issue by BDonnot** [rte-france/Grid2Op#233]
The main installed packages are listed below.

In your submission, you can only use the package listed there.

During the warmup phase, if you need other packages we can see if it's possible to install them and they will be available for the validation and test phases.

The script that scores the submission run on the `bdonnot/l2rpn:icaps.2021.4` docker images, you can retrieve it with `docker pull bdonnot/l2rpn:icaps.2021.4` and use it locally to be as close as possible to the evaluation script.

Otherwise, you can install the specific version of these packages in a virtual env as explained in the last part of this post.

**NB** you can use any package you want during training of your agent (if they need training), to find hyper parameters etc. These packages are only used for evaluating how well your submission performs. For example, you could use any RL framework you want to train an agent. And once the policy is trained, you load it using tensorflow and use this tensorflow model in codalab. This causes absolutely no trouble.

# Standard packages

- numpy '1.19.5'
- scipy '1.6.0'
- pandas '1.2.4'
- pandas '1.2.4'
- numba "0.53.0"
- statsmodels "0.12.2"

# Power system / grid2op ecosystem

- pandapower "2.6.0"
- grid2op "1.6.3"
- lightsim2grid "0.5.4"
- l2rpn_baselines "0.5.1"

# Deep learning and reinforcement learning libraries

- torch '1.8.1+cpu'
- torch_geometric '1.7.0'
- tensorflow '2.5.0'
- tensorflow_probability '0.12.2'
- tensorboard '2.5.0'
- paddle "2.1.0"
- tianshou "0.4.1"
- ray "1.5.0" (with RL Lib)
- stable_baselines3 "1.0"
- acme  "0.2.1"
- sonnet "2.0.0"
- gym "0.18.3"
- spektral "1.0.6"
- dopamine-rl 3.1.14
- maze-rl 0.1.7
- dgl 0.7.0

# Optimization libraries

- nevergrad "0.4.3.post4"
- bayes_opt "1.2.0"
- pypsa "0.17.1"
- ortools "9.0.9048" (available solvers: GLOP, CBC, CLP and BOP)
-  cvxpy "1.1.13"
- jax "0.2.14"
- pyomo "6.0.1" (with solvers: cbc and glpk)

# Complete list

 Here is the list, in no particular order (it can be a pain to install all these packages at these versions due to some dependencies: for example cvxpy works if ecos is installed. But you need to install a specific version of ecos to be compatible with numpy 1.19.5 otherwise you cannot import it)

absl-py==0.13.0
- aiohttp==3.7.4.post0
- aiohttp-cors==0.7.0
- aioredis==1.3.1
- antlr4-python3-runtime==4.8
- ase==3.21.1
- astor==0.8.1
- astunparse==1.6.3
- async-timeout==3.0.1
- atari-py==0.2.9
- attrs==21.2.0
- bayesian-optimization==1.2.0
- blessings==1.7
- cachetools==4.2.2
- certifi==2021.5.30
- cffi==1.14.5
- chardet==4.0.0
- chex==0.0.8
- click==8.0.1
- cloudpickle==1.6.0
- cma==3.0.3
- colorama==0.4.4
- colorful==0.5.4
- cryptography==3.4.7
- cvxpy==1.1.13
- cycler==0.10.0
- decorator==4.4.2
- dgl==0.7.0
- dm-acme==0.2.1
- dm-env==1.4
- dm-reverb-nightly==0.3.0.dev20210727
- dm-sonnet==2.0.0
- dm-tree==0.1.6
- dopamine-rl==3.1.14
- ecos==2.0.5
- et-xmlfile==1.1.0
- filelock==3.0.12
- flatbuffers==1.12
- flax==0.3.4
- gast==0.4.0
- gin-config==0.4.0
- google-api-core==1.30.0
- google-auth==1.31.0
- google-auth-oauthlib==0.4.4
- google-pasta==0.2.0
- googleapis-common-protos==1.53.0
- googledrivedownloader==0.4
- gpustat==0.6.0
- Grid2Op==1.6.3
- grpcio==1.34.1
- gym==0.18.3
- h5py==3.1.0
- hiredis==2.0.0
- hydra-core==1.1.0
- hydra-nevergrad-sweeper==1.1.5
- idna==2.10
- imageio==2.9.0
- importlib-resources==5.2.0
- iniconfig==1.1.1
- isodate==0.6.0
- jax==0.2.14
- jaxlib==0.1.67
- Jinja2==3.0.1
- joblib==1.0.1
- jsonschema==3.2.0
- keras-nightly==2.5.0.dev2021032900
- Keras-Preprocessing==1.1.2
- kiwisolver==1.3.1
- l2rpn-baselines==0.5.1
- LightSim2Grid @ file:///lightsim2grid (0.5.4)
- llvmlite==0.36.0
- lxml==4.6.3
- lz4==3.1.3
- Markdown==3.3.4
- MarkupSafe==2.0.1
- matplotlib==3.4.2
- maze-rl==0.1.7
- mirakuru==2.4.1
- msgpack==1.0.2
- multidict==5.1.0
- networkx==2.5.1
- nevergrad==0.4.3.post4
- numba==0.53.0
- numexpr==2.7.3
- numpy==1.19.5
- nvidia-ml-py3==7.352.0
- oauthlib==3.1.1
- omegaconf==2.1.0
- opencensus==0.7.13
- opencensus-context==0.1.2
- opencv-python==4.5.2.54
- opencv-python-headless==4.3.0.36
- openpyxl==3.0.7
- opt-einsum==3.3.0
- optax==0.0.9
- ortools==9.0.9048
- osqp==0.6.2.post0
- packaging==20.9
- paddlepaddle==2.1.0
- pandapower==2.6.0
- pandas==1.2.4
- patsy==0.5.1
- Pillow==8.2.0
- pluggy==0.13.1
- ply==3.11
- port-for==0.6.1
- portpicker==1.4.0
- prometheus-client==0.11.0
- protobuf==3.17.3
- psutil==5.8.0
- py==1.10.0
- py-spy==0.3.7
- pyasn1==0.4.8
- pyasn1-modules==0.2.8
- pybind11==2.6.2
- pycparser==2.20
- pydantic==1.8.2
- pygame==2.0.1
- pygifsicle==1.0.4
- pyglet==1.5.15
- Pympler==0.9
- Pyomo==6.0.1
- pyparsing==2.4.7
- pypsa==0.17.1
- pyrsistent==0.17.3
- pytest==6.2.4
- pytest-redis==2.1.1
- pytest-timeout==1.4.2
- python-dateutil==2.8.1
- python-louvain==0.15
- pytz==2021.1
- PyYAML==5.4.1
- qdldl==0.1.5.post0
- ray==1.5.0
- rdflib==5.0.0
- redis==3.5.3
- requests==2.25.1
- requests-oauthlib==1.3.0
- rsa==4.7.2
- scikit-learn==0.24.2
- scipy==1.6.0
- scs==2.1.4
- seaborn==0.11.1
- six==1.15.0
- spektral==1.0.6
- stable-baselines3==1.0
- statsmodels==0.12.2
- tables==3.6.1
- tabulate==0.8.9
- tensorboard==2.5.0
- tensorboard-data-server==0.6.1
- tensorboard-plugin-wit==1.8.0
- tensorboardX==2.2
- tensorflow==2.5.0
- tensorflow-addons==0.13.0
- tensorflow-estimator==2.5.0
- tensorflow-probability==0.12.2
- termcolor==1.1.0
- tf-slim==1.1.0
- threadpoolctl==2.1.0
- tianshou==0.4.1
- toml==0.10.2
- toolz==0.11.1
- torch==1.8.1+cpu
- torch-cluster==1.5.9
- torch-geometric==1.7.0
- torch-scatter==2.0.7
- torch-sparse==0.6.9
- torch-spline-conv==1.2.1
- torchaudio==0.8.1
- torchvision==0.9.1+cpu
- tqdm==4.61.1
- typeguard==2.12.1
- typing-extensions==3.7.4.3
- urllib3==1.26.5
- Werkzeug==2.0.1
- wrapt==1.12.1
- xlrd==2.0.1
- XlsxWriter==1.4.3
- yarl==1.6.3
- zipp==3.5.0

# Replicating locally the setup without docker

This is an example on how to set up your machine to be as close as possible to the environment used to score your submission. We show it an example on an Ubuntu machine. You will need to adapt it if you use another operating system.

The most simple way to replicate the scoring environment is through docker by running your script in the `bdonnot/l2rpn:icaps.2021.1` image. These explanations are given as an example and **WITHOUT ANY GUARANTEE**.

Other you can: 
- install the solvers: `apt install -y coinor-cbc coinor-clp glpk-utils libglpk-dev ffmpeg libsm6 libxext6`
- create a virtual environment: `python3 -m virtualenv venv`
- tell python to use this virtual environment: `source venv/bin/activate` (this step will be mandatory each time you will want to use your local copy of the environment)
- install a first batch of packages:
```bash
pip3 install -U absl-py==0.13.0 \
                aiohttp==3.7.4.post0 \
                aiohttp-cors==0.7.0 \
                aioredis==1.3.1 \
                ase==3.21.1 \
                astor==0.8.1 \
                astunparse==1.6.3  \
                async-timeout==3.0.1  \
                atari-py==0.2.9  \
                attrs==21.2.0  \
                blessings==1.7  \
                cachetools==4.2.2  \
                certifi==2021.5.30  \
                cffi==1.14.5 \
                chardet==4.0.0 \
                click==8.0.1 \
                cloudpickle==1.6.0 \
                cma==3.0.3 \
                colorama==0.4.4 \
                colorful==0.5.4 \
                cryptography==3.4.7 \
                cycler==0.10.0 \
                decorator==4.4.2 \
                et-xmlfile==1.1.0 \
                filelock==3.0.12 \
                flatbuffers==1.12 \
                gast==0.4.0 \
                google-api-core==1.30.0 \
                google-auth==1.31.0 \
                google-auth-oauthlib==0.4.4 \
                google-pasta==0.2.0 \
                googleapis-common-protos==1.53.0 \
                googledrivedownloader==0.4  \
                gpustat==0.6.0 \
                grpcio==1.34.1 \
                h5py==3.1.0 \
                hiredis==2.0.0 \
                idna==2.10 \
                imageio==2.9.0 \
                isodate==0.6.0 \
                Jinja2==3.0.1 \
                joblib==1.0.1 \
                jsonschema==3.2.0 \
                keras-nightly==2.5.0.dev2021032900 \
                Keras-Preprocessing==1.1.2 \
                kiwisolver==1.3.1 \
                llvmlite==0.36.0 \
                lxml==4.6.3 \
                lz4==3.1.3 \
                Markdown==3.3.4 \
                MarkupSafe==2.0.1 \
                matplotlib==3.4.2 \
                msgpack==1.0.2 \
                multidict==5.1.0 \
                networkx==2.5.1 \
                numba==0.53.0 \
                numexpr==2.7.3 \
                numpy==1.19.5 \
                nvidia-ml-py3==7.352.0 \
                oauthlib==3.1.1 \
                opencensus==0.7.13 \
                opencensus-context==0.1.2 \
                opencv-python==4.5.2.54 \
                opencv-python-headless==4.3.0.36 \
                openpyxl==3.0.7 \
                opt-einsum==3.3.0 \
                osqp==0.6.2.post0 \
                packaging==20.9 \
                pandas==1.2.4 \
                patsy==0.5.1 \
                Pillow==8.2.0 \
                ply==3.11 \
                portpicker==1.4.0 \
                prometheus-client==0.11.0 \
                protobuf==3.17.3 \
                psutil==5.8.0 \
                py-spy==0.3.7 \
                pyasn1==0.4.8 \
                pyasn1-modules==0.2.8 \
                pybind11==2.6.2 \
                pycparser==2.20 \
                pydantic==1.8.2 \
                pygifsicle==1.0.4 \
                pyglet==1.5.15 \
                Pympler==0.9 \
                pyparsing==2.4.7 \
                pyrsistent==0.17.3 \
                python-dateutil==2.8.1 \
                python-louvain==0.15 \
                pytz==2021.1 \
                PyYAML==5.4.1 \
                qdldl==0.1.5.post0 \
                rdflib==5.0.0 \
                redis==3.5.3 \
                requests==2.25.1 \
                requests-oauthlib==1.3.0 \
                rsa==4.7.2 \
                scipy==1.6.0 \
                scs==2.1.4 \
                six==1.15.0 \
                tables==3.6.1 \
                tabulate==0.8.9 \
                termcolor==1.1.0 \
                threadpoolctl==2.1.0 \
                tqdm==4.61.1 \
                typeguard==2.12.1 \
                typing-extensions==3.7.4.3 \
                urllib3==1.26.5 \
                Werkzeug==2.0.1 \
                wrapt==1.12.1 \
                xlrd==2.0.1 \
                XlsxWriter==1.4.3 \
                yarl==1.6.3 \
                chex==0.0.8 \
                toolz==0.11.1 \
                mirakuru==2.4.1 \
                port_for==0.6.1 \
                zipp==3.5.0 \
                pluggy==0.13.1 \
                toml==0.10.2 \
                py==1.10.0 \
                iniconfig==1.1.1 \
                importlib_resources==5.2.0 \
                omegaconf==2.1.0 \
                antlr4-python3-runtime==4.8 \
                optax==0.0.9 \
                hydra_core==1.1.0 \
                hydra-nevergrad-sweeper==1.1.5 \
                pytest_timeout==1.4.2 \
                pytest_redis==2.1.1 \
                seaborn==0.11.1 \
                pytest==6.2.4 \
                flax==0.3.4 \
                pygame==2.0.1
```
- install a second and third batch of python packages (if you do it all at once, it is unlikely to work...)
```bash
pip install -U ecos==2.0.5
pip install -U cvxpy==1.1.13
```
- and guess what, you also need a fourth batch of install, you are so lucky today:
```bash
python3 -m pip install gym==0.18.3 \
                           "ortools==9.0.9048" \
                           "jax==0.2.14" \
                           "jaxlib==0.1.67"  \
                           "dm-acme[reverb]==0.2.1"  \
                           "dm-sonnet==2.0.0" \
                           dm_env==1.4 \
                           "bayesian-optimization==1.2.0"  \
                           "nevergrad==0.4.3.post4"  \
                           dopamine-rl==3.1.14 \
                            tensorboard==2.5.0 \
                            tensorboard-data-server==0.6.1 \
                            tensorboard-plugin-wit==1.8.0 \
                            tensorboardX==2.2 \
                            tensorflow==2.5.0 \
                            tensorflow-addons==0.13.0 \
                            tensorflow-estimator==2.5.0 \
                            tensorflow-probability==0.12.2 \
                           "pandapower==2.6.0"  \
                           "statsmodels==0.12.2"  \
                           "scikit-learn==0.24.2" \
                           "ray[rllib,default]==1.5.0" \
                           "stable-baselines3[extra]==1.0" \
                           "tianshou==0.4.1"  \
                           spektral==1.0.6 \
                           "torch==1.8.1+cpu" \
                           "torchvision==0.9.1+cpu" \
                           "torchaudio==0.8.1" \
                            -f https://download.pytorch.org/whl/lts/1.8/torch_lts.html \
                            "Pyomo==6.0.1" \
                            pypsa=="0.17.1" \
                            "paddlepaddle==2.1.0" \
                            maze-rl==0.1.7 \
                            tf_slim==1.1.0 \
                            gin_config==0.4.0 \
                            dgl==0.7.0 -f https://data.dgl.ai/wheels/repo.html

```
- but wait, there is more
```bash
pip install torch-scatter==2.0.7 -f https://pytorch-geometric.com/whl/torch-1.8.0+cpu.html torch-sparse==0.6.9 -f https://pytorch-geometric.com/whl/torch-1.8.0+cpu.html torch-cluster==1.5.9 -f https://pytorch-geometric.com/whl/torch-1.8.0+cpu.html torch-spline-conv==1.2.1 -f https://pytorch-geometric.com/whl/torch-1.8.0+cpu.html
```
- still not over yet...
```bash
pip3 install -U grid2op==1.6.3 --no-deps  # dependencies are installed manually for more control
pip3 install -U l2rpn-baselines==0.5.1 --no-deps  # dependencies are installed manually for more control
```
- almost there, looking good, you simply now need to install lightsim2grid (approx 15 times faster than the default pandapower backend) for that we forward you to the official installation guide: https://github.com/BDonnot/lightsim2grid/#installation-from-source-recommended

And now your are good to go.

**Comment by kamil-kaczmarek** [comment]
hi @BDonnot ,

I just checked the list of packages for the ICAPS 2021 competition. I just wanted to ask if it's ok to add this lib:
https://github.com/dmlc/dgl

(install instructions: https://www.dgl.ai/pages/start.html)

**Comment by BDonnot** [comment]
It makes sense indeed. I'll try to include it for the validation phase (need to check for possible incompatibility issues)

**Comment by kamil-kaczmarek** [comment]
Great, thank you.

**Comment by BDonnot** [comment]
# As a reminder: the original post, BEFORE i updated the packages
# DO NOT USE

The main installed packages are listed below.

In your submission, you can only use the package listed there.

During the warmup phase, if you need other packages we can see if it's possible to install them and they will be available for the validation and test phases.

The script that scores the submission run on the `bdonnot/l2rpn:icaps.2021.1` docker images, you can retrieve it with `docker pull bdonnot/l2rpn:icaps.2021.1` and use it locally to be as close as possible to the evaluation script.

Otherwise, you can install the specific version of these packages in a virtual env as explained in the last part of this post.

**NB** you can use any package you want during training of your agent (if they need training), to find hyper parameters etc. These packages are only used for evaluating how well your submission performs. For example, you could use any RL framework you want to train an agent. And once the policy is trained, you load it using tensorflow and use this tensorflow model in codalab. This causes absolutely no trouble.

# Standard packages

- numpy '1.19.5'
- scipy '1.6.0'
- pandas '1.2.4'
- pandas '1.2.4'
- numba "0.53.0"
- statsmodels "0.12.2"

# Power system / grid2op ecosystem

- pandapower "2.6.0"
- grid2op "1.6.0.post1"
- lightsim2grid "0.5.1"
- l2rpn_baselines "0.5.1"

# Deep learning and reinforcement learning libraries

- torch '1.8.1+cpu'
- torch_geometric '1.7.0'
- tensorflow '2.5.0'
- tensorflow_probability '0.12.2'
- tensorboard '2.5.0'
- paddle "2.1.0"
- tianshou "0.4.1"
- ray "1.4.0" (with RL Lib)
- stable_baselines3 "1.0"
- acme  "0.2.1"
- sonnet "2.0.0"
- gym "0.18.3"
- spektral "1.0.6"
- dopamine-rl 3.1.14

# Optimization libraries

- nevergrad "0.4.3.post4"
- bayes_opt "1.2.0"
- pypsa "0.17.1"
- ortools "9.0.9048" (available solvers: GLOP, CBC, CLP and BOP)
-  cvxpy "1.1.13"
- jax "0.2.14"
- pyomo "6.0.1" (with solvers: cbc and glpk)

# Complete list

 Here is the list, in no particular order (it can be a pain to install all these packages at these versions due to some dependencies: for example cvxpy works if ecos is installed. But you need to install a specific version of ecos to be compatible with numpy 1.19.5 otherwise you cannot import it)

- absl-py 0.13.0
- aiohttp 3.7.4.post0
- aiohttp-cors 0.7.0
- aioredis 1.3.1
- ase 3.21.1
- astor 0.8.1
- astunparse 1.6.3 
- async-timeout 3.0.1 
- atari-py 0.2.9 
- attrs 21.2.0 
- blessings 1.7 
- cachetools 4.2.2 
- certifi 2021.5.30 
- cffi 1.14.5
- chardet 4.0.0
- click 8.0.1
- cloudpickle 1.6.0
- cma 3.0.3
- colorama 0.4.4
- colorful 0.5.4
- cryptography 3.4.7
- cycler 0.10.0
- decorator 4.4.2
- et-xmlfile 1.1.0
- filelock 3.0.12
- flatbuffers 1.12
- gast 0.4.0
- google-api-core 1.30.0
- google-auth 1.31.0
- google-auth-oauthlib 0.4.4
- google-pasta 0.2.0
- googleapis-common-protos 1.53.0
- googledrivedownloader 0.4 
- gpustat 0.6.0
- grpcio 1.34.1
- h5py 3.1.0
- hiredis 2.0.0
- idna 2.10
- imageio 2.9.0
- isodate 0.6.0
- Jinja2 3.0.1
- joblib 1.0.1
- jsonschema 3.2.0
- keras-nightly 2.5.0.dev2021032900
- Keras-Preprocessing 1.1.2
- kiwisolver 1.3.1
- l2rpn-baselines 0.5.1
- llvmlite 0.36.0
- lxml 4.6.3
- lz4 3.1.3
- Markdown 3.3.4
- MarkupSafe 2.0.1
- matplotlib 3.4.2
- msgpack 1.0.2
- multidict 5.1.0
- networkx 2.5.1
- numba 0.53.0
- numexpr 2.7.3
- numpy 1.19.5
- nvidia-ml-py3 7.352.0
- oauthlib 3.1.1
- opencensus 0.7.13
- opencensus-context 0.1.2
- opencv-python 4.5.2.54
- opencv-python-headless 4.3.0.36
- openpyxl 3.0.7
- opt-einsum 3.3.0
- osqp 0.6.2.post0
- packaging 20.9
- pandas 1.2.4
- patsy 0.5.1
- Pillow 8.2.0
- ply 3.11
- portpicker 1.4.0
- prometheus-client 0.11.0
- protobuf 3.17.3
- psutil 5.8.0
- py-spy 0.3.7
- pyasn1 0.4.8
- pyasn1-modules 0.2.8
- pybind11 2.6.2
- pycparser 2.20
- pydantic 1.8.2
- pygifsicle 1.0.4
- pyglet 1.5.15
- Pympler 0.9
- pyparsing 2.4.7
- pyrsistent 0.17.3
- python-dateutil 2.8.1
- python-louvain 0.15
- pytz 2021.1
- PyYAML 5.4.1
- qdldl 0.1.5.post0
- rdflib 5.0.0
- redis 3.5.3
- requests 2.25.1
- requests-oauthlib 1.3.0
- rsa 4.7.2
- scipy 1.6.0
- scs 2.1.4
- six 1.15.0
- tables 3.6.1
- tabulate 0.8.9
- termcolor 1.1.0
- threadpoolctl 2.1.0
- tqdm 4.61.1
- typeguard 2.12.1
- typing-extensions 3.7.4.3
- urllib3 1.26.5
- Werkzeug 2.0.1
- wrapt 1.12.1
- xlrd 2.0.1
- XlsxWriter 1.4.3
- yarl 1.6.3
- gym 0.18.3
- "ortools 9.0.9048"
- "jax 0.2.14"
- "jaxlib 0.1.67" 
- "dm-acme[reverb] 0.2.1" 
- "dm-sonnet 2.0.0"
- "bayesian-optimization 1.2.0" 
- "nevergrad 0.4.3.post4" 
- tensorboard 2.5.0
- tensorboard-data-server 0.6.1
- tensorboard-plugin-wit 1.8.0
- tensorboardX 2.2
- tensorflow 2.5.0
- tensorflow-addons 0.13.0
- tensorflow-estimator 2.5.0
- tensorflow-probability 0.12.2
- "pandapower 2.6.0" 
- "statsmodels 0.12.2" 
- "scikit-learn 0.24.2"
- "ray[rllib,default] 1.4.0"
- "stable-baselines3[extra] 1.0"
- "tianshou 0.4.1" 
- spektral 1.0.6
- "torch 1.8.1+cpu"
- "torchvision 0.9.1+cpu"
- "torchaudio 0.8.1"
- "Pyomo 6.0.1"
- pypsa "0.17.1"
- "paddlepaddle 2.1.0"
- torch-scatter 2.0.7 
- torch-sparse 0.6.9 
- orch-cluster 1.5.9 
- torch-spline-conv 1.2.1
- "torch-geometric 1.7.0"
- grid2op 1.6.0
- l2rpn-baselines 0.5.1
- lightsim2grid 0.5.1
- ecos 2.0.5
- cvxpy 1.1.13
- dopamine-rl 3.1.14

# Replicating locally the setup without docker

This is an example on how to set up your machine to be as close as possible to the environment used to score your submission. We show it an example on an Ubuntu machine. You will need to adapt it if you use another operating system.

The most simple way to replicate the scoring environment is through docker by running your script in the `bdonnot/l2rpn:icaps.2021.1` image. These explanations are given as an example and **WITHOUT ANY GUARANTEE**.

Other you can: 
- install the solvers: `apt install -y coinor-cbc coinor-clp glpk-utils libglpk-dev ffmpeg libsm6 libxext6`
- create a virtual environment: `python3 -m virtualenv venv`
- tell python to use this virtual environment: `source venv/bin/activate` (this step will be mandatory each time you will want to use your local copy of the environment)
- install a first batch of packages:
```bash
pip3 install -U absl-py==0.13.0 \
                aiohttp==3.7.4.post0 \
                aiohttp-cors==0.7.0 \
                aioredis==1.3.1 \
                ase==3.21.1 \
                astor==0.8.1 \
                astunparse==1.6.3  \
                async-timeout==3.0.1  \
                atari-py==0.2.9  \
                attrs==21.2.0  \
                blessings==1.7  \
                cachetools==4.2.2  \
                certifi==2021.5.30  \
                cffi==1.14.5 \
                chardet==4.0.0 \
                click==8.0.1 \
                cloudpickle==1.6.0 \
                cma==3.0.3 \
                colorama==0.4.4 \
                colorful==0.5.4 \
                cryptography==3.4.7 \
                cycler==0.10.0 \
                decorator==4.4.2 \
                et-xmlfile==1.1.0 \
                filelock==3.0.12 \
                flatbuffers==1.12 \
                gast==0.4.0 \
                google-api-core==1.30.0 \
                google-auth==1.31.0 \
                google-auth-oauthlib==0.4.4 \
                google-pasta==0.2.0 \
                googleapis-common-protos==1.53.0 \
                googledrivedownloader==0.4  \
                gpustat==0.6.0 \
                grpcio==1.34.1 \
                h5py==3.1.0 \
                hiredis==2.0.0 \
                idna==2.10 \
                imageio==2.9.0 \
                isodate==0.6.0 \
                Jinja2==3.0.1 \
                joblib==1.0.1 \
                jsonschema==3.2.0 \
                keras-nightly==2.5.0.dev2021032900 \
                Keras-Preprocessing==1.1.2 \
                kiwisolver==1.3.1 \
                llvmlite==0.36.0 \
                lxml==4.6.3 \
                lz4==3.1.3 \
                Markdown==3.3.4 \
                MarkupSafe==2.0.1 \
                matplotlib==3.4.2 \
                msgpack==1.0.2 \
                multidict==5.1.0 \
                networkx==2.5.1 \
                numba==0.53.0 \
                numexpr==2.7.3 \
                numpy==1.19.5 \
                nvidia-ml-py3==7.352.0 \
                oauthlib==3.1.1 \
                opencensus==0.7.13 \
                opencensus-context==0.1.2 \
                opencv-python==4.5.2.54 \
                opencv-python-headless==4.3.0.36 \
                openpyxl==3.0.7 \
                opt-einsum==3.3.0 \
                osqp==0.6.2.post0 \
                packaging==20.9 \
                pandas==1.2.4 \
                patsy==0.5.1 \
                Pillow==8.2.0 \
                ply==3.11 \
                portpicker==1.4.0 \
                prometheus-client==0.11.0 \
                protobuf==3.17.3 \
                psutil==5.8.0 \
                py-spy==0.3.7 \
                pyasn1==0.4.8 \
                pyasn1-modules==0.2.8 \
                pybind11==2.6.2 \
                pycparser==2.20 \
                pydantic==1.8.2 \
                pygifsicle==1.0.4 \
                pyglet==1.5.15 \
                Pympler==0.9 \
                pyparsing==2.4.7 \
                pyrsistent==0.17.3 \
                python-dateutil==2.8.1 \
                python-louvain==0.15 \
                pytz==2021.1 \
                PyYAML==5.4.1 \
                qdldl==0.1.5.post0 \
                rdflib==5.0.0 \
                redis==3.5.3 \
                requests==2.25.1 \
                requests-oauthlib==1.3.0 \
                rsa==4.7.2 \
                scipy==1.6.0 \
                scs==2.1.4 \
                six==1.15.0 \
                tables==3.6.1 \
                tabulate==0.8.9 \
                termcolor==1.1.0 \
                threadpoolctl==2.1.0 \
                tqdm==4.61.1 \
                typeguard==2.12.1 \
                typing-extensions==3.7.4.3 \
                urllib3==1.26.5 \
                Werkzeug==2.0.1 \
                wrapt==1.12.1 \
                xlrd==2.0.1 \
                XlsxWriter==1.4.3 \
                yarl==1.6.3
```
- install a second and third batch of python packages (if you do it all at once, it is unlikely to work...)
```bash
pip install -U ecos==2.0.5
pip install -U cvxpy==1.1.13
```
- and guess what, you also need a fourth batch of install, you are so lucky today:
```bash
pip install gym==0.18.3 \
                           "ortools==9.0.9048" \
                           "jax==0.2.14" \
                           "jaxlib==0.1.67"  \
                           "dm-acme[reverb]==0.2.1"  \
                           "dm-sonnet==2.0.0" \
                           "bayesian-optimization==1.2.0"  \
                           "nevergrad==0.4.3.post4"  \
                            tensorboard==2.5.0 \
                            tensorboard-data-server==0.6.1 \
                            tensorboard-plugin-wit==1.8.0 \
                            tensorboardX==2.2 \
                            tensorflow==2.5.0 \
                            tensorflow-addons==0.13.0 \
                            tensorflow-estimator==2.5.0 \
                            tensorflow-probability==0.12.2 \
                           "pandapower==2.6.0"  \
                           "statsmodels==0.12.2"  \
                           "scikit-learn==0.24.2" \
                           "ray[rllib,default]==1.4.0" \
                           "stable-baselines3[extra]==1.0" \
                           "tianshou==0.4.1"  \
                           spektral==1.0.6 \
                           "torch==1.8.1+cpu" \
                           "torchvision==0.9.1+cpu" \
                           "torchaudio==0.8.1" \
                            -f https://download.pytorch.org/whl/lts/1.8/torch_lts.html \
                            "Pyomo==6.0.1" \
                            pypsa=="0.17.1" \
                            "paddlepaddle==2.1.0" \
                           dopamine-rl==3.1.14

```
- but wait, there is more
```bash
pip install torch-scatter==2.0.7 -f https://pytorch-geometric.com/whl/torch-1.8.0+cpu.html torch-sparse==0.6.9 -f https://pytorch-geometric.com/whl/torch-1.8.0+cpu.html torch-cluster==1.5.9 -f https://pytorch-geometric.com/whl/torch-1.8.0+cpu.html torch-spline-conv==1.2.1 -f https://pytorch-geometric.com/whl/torch-1.8.0+cpu.html
```
- still not over yet...
```bash
pip install -U grid2op==1.6.0.post1 --no-deps  # dependencies are installed manually for more control
pip install -U l2rpn-baselines==0.5.1 --no-deps  # dependencies are installed manually for more control
```
- almost there, looking good, you simply now need to install lightsim2grid (approx 15 times faster than the default pandapower backend) for that we forward you to the official installation guide: https://github.com/BDonnot/lightsim2grid/#installation-from-source-recommended

And now your are good to go.


# End Reminder
# END DO NOT USE
