### ISSUE TITLE
Bug when simulating an action leading to a diverging powerflow with LightSim

### ISSUE THREAD

**Issue by marota** [rte-france/Grid2Op#235]
## Environment
 - Grid2op version: `1.6.0`
 - System: ` osx`
 - Additional system information

## Bug description

Bug when simulating an action leading to a diverging powerflow with LightSim.

### Code snippet

```python

import grid2op
# Backend class to use
from lightsim2grid.LightSimBackend import LightSimBackend
BACKEND = LightSimBackend
#from grid2op.Backend import PandaPowerBackend
#BACKEND = PandaPowerBackend

env_path='/YourPath/L2RPN_icaps2021/input_data_val'

env = grid2op.make(env_path,backend=BACKEND(),difficulty="competition")

final_dict={'generators_id': [(19, 1)],
 'loads_id': [(30, 2)],
 'lines_or_id': [(58, 1)],
 'lines_ex_id': [(46, 1), (47, 2)]}
action=env.action_space({"set_bus": final_dict})

obs=env.get_obs()
obs.simulate(action,time_step=0)


```

## Current output

  File "grid2op/Observation/CompleteObservation.py", line 206, in update
    self._shunt_p[:] = sh_p
ValueError: could not broadcast input array from shape (0) into shape (6)

When doing env.step(action) your get the following:

(<grid2op.Space.GridObjects.CompleteObservation_input_data_val at 0x7f815e84aa60>,
 -1.0,
 True,
 {'disc_lines': array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
         -1, -1, -1, -1, -1,  1,  1, -1, -1, -1, -1, -1, -1, -1,  1,  1,  1,
          1,  1,  1,  1,  1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  0,
          0, -1, -1, -1, -1, -1, -1, -1], dtype=int32),
  'is_illegal': False,
  'is_ambiguous': False,
  'is_dispatching_illegal': False,
  'is_illegal_reco': False,
  'reason_alarm_illegal': None,
  'opponent_attack_line': None,
  'opponent_attack_sub': None,
  'opponent_attack_duration': 0,
  'exception': [Grid2OpException DivergingPowerFlow DivergingPowerFlow('divergence of powerflow (non connected grid)')],
  'rewards': {}})

Or doing the same simulate but with pandapower you get:

(<grid2op.Space.GridObjects.CompleteObservation_input_data_val at 0x7fd3ab019eb0>,
 -1.0,
 True,
 {'disc_lines': array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
         -1, -1, -1, -1, -1,  1,  1, -1, -1, -1, -1, -1, -1, -1,  1,  1,  1,
          1,  1,  1,  1,  1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  0,
          0, -1, -1, -1, -1, -1, -1, -1], dtype=int32),
  'is_illegal': False,
  'is_ambiguous': False,
  'is_dispatching_illegal': False,
  'is_illegal_reco': False,
  'reason_alarm_illegal': None,
  'opponent_attack_line': None,
  'opponent_attack_sub': None,
  'opponent_attack_duration': 0,
  'exception': [Grid2OpException DivergingPowerFlow DivergingPowerFlow('powerflow diverged with error :"Power Flow nr did not converge after 10 iterations!"')],
  'rewards': {}})

## Expected output

```
Would expect the same kind of output as pandapower
```

**Comment by BDonnot** [comment]
Should be fixed in the latest grid2op release (version 1.6.0.post1)
