### ISSUE TITLE
Can not inspect the agent by "runner.env.action_space.from_vect(all_actions[i,:])"

### ISSUE THREAD

**Issue by roki1031** [rte-france/Grid2Op#256]
## Environment
 - Grid2op version: `1.6.3`
 - System: `windows`
 - Python:3.8

## Bug description

Can not inspect the agent by `runner.env.action_space.from_vect(all_actions[i,:])`
instead, it would raise a exception as **"'Runner' object has no attribute 'env'"**
if i change above to  `runner.envClass.action_space.from_vect(all_actions[i,:])` . It will prompt error **"'property' object has no attribute 'from_vect'".**

## How to reproduce

```python
from grid2op.Runner import Runner
from tqdm.notebook import tqdm
from grid2op.Reward import L2RPNReward
scoring_function = L2RPNReward 
path_save_results = "{}_results".format(save_path)

from l2rpn_baselines.DuelQSimple import DuelQSimple
from l2rpn_baselines.DuelQSimple import DuelQ_NNParam
path_model, path_target_model = DuelQ_NNParam.get_path_model(save_path, agent_name)
nn_archi = DuelQ_NNParam.from_json(os.path.join(path_model, "nn_architecture.json"))


my_agent = DuelQSimple(env.action_space, nn_archi, name=agent_name)
my_agent.load(save_path)
my_agent.init_obs_extraction(env.observation_space)


dict_params = env.get_params_for_runner()
dict_params["gridStateclass_kwargs"]["max_iter"] =  max_iter

runner = Runner(**dict_params, agentClass=None, agentInstance=my_agent)

res = runner.run(nb_episode=10, path_save=path_save_results, pbar=tqdm)

from grid2op.Episode import EpisodeData
all_episodes = EpisodeData.list_episode(path_save_results)
this_episode = EpisodeData.from_disk(*all_episodes[0])
all_actions = this_episode.get_actions()
li_actions = []
for i in range(all_actions.shape[0]):
    tmp = runner.envClass.action_space.from_vect(all_actions[i,:])
    li_actions.append(tmp)
```
**EDIT** (benjamin) I formatted your issue properly for the python code.
**EDIT** (benjamin) Please next time use the template bellow to send the code

### Command line

```bash
# command line used if any 
```

### Code snippet

```python
import grid2op

... # Some code 
```

## Current output

```
The output of the code snippet above
```

## Expected output

```
The expected output and/or expected behavior description
```

**Comment by BDonnot** [comment]
Hello,

I think there is a misusage of the function `from_vect` and you are trying to do some things that are already done automatically (especially because they are a bit tricky).

If you want the list of actions from the "EpisodeData" you can consult the documentation https://grid2op.readthedocs.io/en/latest/episode.html Basically, you have to:

```python
import grid2op
from grid2op.Episode import EpisodeData

# I study only the first episode saved, because... why not
path_save_results = ...  # same path as before

li_episode = EpisodeData.list_episode(path_save_results)
this_episode = EpisodeData.from_disk(*li_episode[0])

# now the episode is loaded, and you can easily iterate through the observation, the actions etc.
for act in this_episode.actions:
    print(act)

for i, obs in enumerate(this_episode.observations):
    print("At step {} the active productions were {}".format(i, obs.prod_p))
```

I think the list `this_episode.actions` gives you exactly what you wanted to get in `li_actions`

I am closing the issue, feel free to re open it if I did not understood your problem correctly.
