### ISSUE TITLE
Can I load some unsupported power system as my environment？

### ISSUE THREAD

**Issue by desktoop** [rte-france/Grid2Op#294]
grid2op is a wonderful tool for powerflow and i want to use it into my own research. So i wonder know that if i could load other power system? 
for example:
```python
import grid2op
env_name = "IEEE30"    # a 30-node system 
env = grid2op.make(env_make)
```

If i want to make it, what should I do?

**Comment by BDonnot** [comment]
Hello,

Glad to see that grid2op suits you and you want to use it :-)

Yes it's entirely possible, utlimately a "grid2op environment" is just a folder on a computer with (in short):
- a file describing a power grid
- a folder describing the production and loads at each time.

If you have everything is should not be hard to create a grid2op environment.

More details are given in the documentation: 
- https://grid2op.readthedocs.io/en/latest/available_envs.html#content-of-an-environment
- https://grid2op.readthedocs.io/en/latest/available_envs.html#possible-workflow-to-create-an-environment-from-existing-chronics


Let me know if you need some more information :-)

**Comment by desktoop** [comment]
Thanks for you reply. I do need some more help about chronics.  Is chronic a term in power grid or reinforcement learning? I want to know how to make my own chronics data from scratch? 

I found there are 1000 folders under chronics directory (rte_case14_realistic/chronics/). I want to figure out the meaning of the number "1000". 1000 topologies? And how to prepare the data (load_p.csv.bz2, load_q.csv.bz2) in each folders?

**Comment by BDonnot** [comment]
Hello,

We started with the "word" "chronix" as a bad translation from the French "chronique" word. It's an "English" word a team of French people invented... Pardon my French as the expression would say ;-)

You can think of the "chronix" as "time series" (this is exactly what is actually).

What they contain is no more (and no less) than value for each step (row) and for each load / generation of the grid (colum).

The "chronix2grid" package, which we are currently refactoring helps you to build such time series if you don't have them already.

What is your usecase exactly, maybe We can help :-)

**Comment by desktoop** [comment]
Here I am using case30 (https://matpower.org/docs/ref/matpower5.0/case30.html) in matlab. 

My task is training a model to predict voltage at each node under different topologies and a group of  given injections

For getting topology variants:
1. I randomly disconnect one of the branch in this power system for 100 times. (some of them can't converge well, but they don't matters)
2. For each variants, I have solved the ac-pf equations 1000 times with sampling power injection in each time by MATPOWER.
3. After 1 and 2, I have generated 100 topologies and 100*1000 data pairs ([injection, voltage]). then I need to build an environment for training.

For the backend, I am still going to use pandapower backend as default, because it's easy to convert .m file to .json file via pandapower. 

And here is my problem, how to use my data to build a environment for me? Is my data sufficient or appropriate to do that?

btw, my data is not in time-series form due to my task is time independent.

**Comment by BDonnot** [comment]
> btw, my data is not in time-series form due to my task is time independent.

Yep, no problem at all for grid2op, it works equally well with non temporal data. I would recommend not using reinforcement learning if you don't need to work with time component here.

> And here is my problem, how to use my data to build a environment for me? Is my data sufficient or appropriate to do that?

From what I understood, yes it totally is. If you give me a sample or your data (if you can) I can do one for you if you want so you can have a starting point.

> My task is training a model to predict voltage at each node under different topologies and a group of given injections
To be totally honest with you, i think you did all the hard work in matlab and don't need grid2op (or pandapower) at all here.

I would save your results [injections, topologies, voltages] as a csv file (for example) and then use tensorflow / pytorch / scikit learn / xg boost / etc. to learn from these data.
I did pretty much the same work during my PhD and I found out that the "LeapNet" architecture (which I developed) worked really nicely to predict this even when you ask it to predict unseen topologies (in your case when you disconnect 2 powerlines). You can find some code there https://github.com/BDonnot/leap_net if you want.

# If you still want to use grid2op / pandapower

## Create an environment: method 1
Also, if you want to use grid2op, i would suggest going back from the start: 
1) you save your "group of given injections" csv files: "prod_p.csv" for the generator active production, "load_p.csv" for the load active consumption, "load_q.csv" for the load reactive, and "prod_v.csv" for the voltage setpoint of each generator (each time you need to have one "row" representing a single "group of injection" and one column represents a generator or a load
2) use pandapower to convert the .m file to a .json file (pretty easy)
3) then grid2op docs should be sufficient to get you started with a grid2op environment
4) [optional] if you want to compute powerflow 20x faster and get the exact same results as pandapower you can use the "lightsim2grid" backend https://github.com/BDonnot/lightsim2grid)


## Create an environment: method 2:
Process is similar but a bit different:
1) find a way to load your data to a numpy array in python. You will end up with 4 arrays: load_p (load active consumption), load_q (load reactive consumption), gen_p (generator active production),  gen_v (generator voltage setpoint). They all have the same number of rows (1000 in your case as you have "1000 data points") and load_p / load_q have the same number of colums which corresponds to the number of loads on your grid (same for gen_p and gen_v, but of course it's the generators)
2) use pandapower to convert the .m file to a json format, save it in a directory
3) use grid2op to load this grid with your injection having the `FromNPY` chornic class
4) same note as above: use lightims2grid :-) 

This looks like:

```python
import grid2op
from grid2op.Chronics import FromNPY

load_p = ...
load_q = ...
gen_p = ...
gen_v = ...

json_grid_file = ...

env = grid2op.make("blank",
                                 test=True,
                                grid_path=json_grid_file,
                                 chronics_class=FromNPY,
                                  data_feeding_kwargs={
                                        "load_p": load_p,
                                        "load_q": load_q,
                                        "prod_p": gen_p,
                                        "prod_v": gen_v}
)
```

## Generate data
Then you can use grid2op to generate your data, easily disconnect / reconnect powerlines etc. (but again, you already did this job in matlab so probably not worth to redo it here, but again it depends on the scope of the project, if you need to sample more data, be more efficient etc.)

What grid2op allows in your case is the to change not only the status connected / disconnected of powerlines (as you did) but also the graph of the grid by allowing you to split a substation into different buses for example (this is far from easy to do with matlab only)

Again the "leap_net" code is perfect for that (let me know if you want some help for that, the leap net code is way less documented and "user friend" than grid2op)

**Comment by desktoop** [comment]
I'm back. But first...... sorry to keep this issue open for a month...... 
In last month, I took some simple research about power grid tools or platforms, and also, read your leap net paper. Thanks again for you advise. I think it's worth trying your model leap net, however, maybe I will not pay more attention on grid2op...... This issue could be closed now.
