### ISSUE TITLE
Setting No Shunts and No Storages in Backend

### ISSUE THREAD

**Issue by MichelleChaoChen** [rte-france/Grid2Op#325]
## Environment
 - Grid2op version: `1.7.0`
 - System: `windows`
 - Additional system information

## Bug description

The bug arises from using a Backend that does not initialise attributes related to shunts or storages though this is supposed to be supported by Grid2Op. The static method `assert_grid_correct` in `GridObjects` class will raise an error when attributes related to shunts and storages are not initialised. Possibly, despite shunts being set to unavailable, the check in `_check_validity_shunt_data` is still performed. The same applies to the checks in `_check_validity_storage_data` 

## How to reproduce

The bug can be reproduced by running the environment with the `EducPandaPowerBackend`. 

### Code snippet

```python
import grid2op
from grid2op.Backend.EducPandaPowerBackend import EducPandaPowerBackend

env = grid2op.make(backend=EducPandaPowerBackend())
```

## Current output

```
AttributeError: 'CompleteObservation_rte_case14_realistic' object has no attribute '_shunt_p'
```

## Expected output

This error should not be raised because the `EducPandaPowerBackend` has set the shunts and storages as unavailable in the `load_grid` method with the following lines: 
```python
self.shunts_data_available = False
self.set_no_storage()
```
And making the changes below still gave the same error when trying to make the environment. 
```python
type(self).shunts_data_available = False
type(self).set_no_storage()
```

**Comment by BDonnot** [comment]
Hi,

This is solved if you install grid2op from github (branch dev_1.7.1). I plan on making it part of grid2op 1.7.1 that will be released soon (I hope by the end of this week - if everything goes well)

In the mean time, you can use a development version you can install with:

`pip install git+https://github.com/rte-france.com/grid2op.git@dev_1.7.1`

or something similar (not 100% certain about the syntax above)

**Comment by BDonnot** [comment]
The fix is now officially part of grid2op since version 1.7.1 (I just released it)
