### ISSUE TITLE
Environment  to_test referenced before assignment

### ISSUE THREAD

**Issue by veinpy** [rte-france/Grid2Op#363]
### Environment
-----
Grid2op version: 1.7.2
System: Linux

### Bug description
----
function train_val_split in Environment class , variable to_test is referenced before assignment 

code snippet
```python
    def train_val_split(
        self,
        val_scen_id,
        add_for_train="train",
        add_for_val="val",
        add_for_test=None,
        test_scen_id=None,
        remove_from_name=None,
        deep_copy=False,
    ):
        """xxxxx"""

        if nm_test is not None:
            os.mkdir(path_test)

        # assign which chronics goes where
        chronics_path = os.path.join(my_path, chronics_dir)
        all_chron = sorted(os.listdir(chronics_path))
        to_val = set(val_scen_id)

        if nm_test is not None:
            to_test = set(test_scen_id)
        else:  "# add else condition for create to_test "
            to_test = set()
        if deep_copy:
            import shutil
```

**Comment by veinpy** [comment]
![image](https://user-images.githubusercontent.com/8607675/180419769-b5918be9-477d-4997-9a79-74d8127099be.png)

**Comment by BDonnot** [comment]
Hello,

Thanks for spotting this bug and provide a solution.

In the mean time I can only recommend you to use this function to split the base environment into training, validation and test set. So that there is no error.

I'll fix it in next version. Which might take a while.
