### ISSUE TITLE
Bug: Wrong changed status on BaseActio.impact_on_objects() for curtailment

### ISSUE THREAD

**Issue by Melon-PieldeSapo** [rte-france/Grid2Op#364]
## Environment
 - Grid2op version: `1.7.2`
 - System: `windows 10`

## Bug description
Bug found doing code inspection:
i think on:
https://github.com/rte-france/Grid2Op/blob/51854262d02d96c1ee1798a78a86661d1ff971a1/grid2op/Action/BaseAction.py#L2814
it should be:
`
            curtailment["changed"] = True
`

## How to reproduce
-

### Command line
-

### Code snippet
-

## Current output
-

## Expected output
-

**Comment by BDonnot** [comment]
Thanks for noticing.

We'll address it asap.
