### ISSUE TITLE
Env L2RPN_WCCI_2022 - A weird substation

### ISSUE THREAD

**Issue by marota** [rte-france/Grid2Op#375]
One substation ("72") has only one line connected to it and nothing else in "l2rpn_wcci_2022":
![image](https://user-images.githubusercontent.com/5496312/203538243-3172fd77-0ff8-4bcf-b9a4-6364e785b4a6.png)

This makes this substation pointless (and also for consistancy you at least expect to have 2 elements per substation). 
So maybe something to check when creating/loading an environment:

"n_sub_elements>=2"
so ```np.all(env.sub_info>=2) ```

**Comment by BDonnot** [comment]
Thanks for noticing.

Can you check in the pandapower file what's on this substation? This is indeed super weird.

And in the original IEEE 118 too.

Thanks

**Comment by marota** [comment]
There seems to be a generator

**Comment by marota** [comment]
And see pandapower

```
import pandapower.networks as pn
net = pn.case118()
net.gen
```

![image](https://user-images.githubusercontent.com/5496312/203989143-dfe1586c-bfd6-462c-97d4-c6295e1383b4.png)
