### ISSUE TITLE
Simulator rho values not correct after calling sim.predict()

### ISSUE THREAD

**Issue by aguerra7002** [rte-france/Grid2Op#377]
## Environment
 - Grid2op version: `1.7.2`
 - System: `ubuntu20.04`

## Bug description
I am trying to use the grid2op `Simulator` class for a model based RL strategy. However, when calling `sim.predict()`, I have noticed that the `rho` values of the resulting observation are close to 0. It appears that the thermal limits are being corrupted somewhere, and I have produced a minimal example below. 

### Code snippet

```
import grid2op

env = grid2op.make('l2rpn_wcci_2022')
obs = env.reset()

# Get the simulator
sim = obs.get_simulator()

# Manually compute rho using thermal limits
rho_old = sim.current_obs.a_or / thermal_limits
print(f"Before Simulation: These should match {sim.current_obs.rho.max()}, {rho_old.max()}")

# Simulate 1 do_nothing action, with loads/gens/etc. staying the same
do_nothing = env.action_space()
new_sim = sim.predict(do_nothing)

# Manually compute new rho, since  the rho from the simulator is wrong.
rho_new = new_sim.current_obs.a_or / thermal_limits
print(f"After Simulation: These should match: {new_sim.current_obs.rho.max()}, {rho_new.max()}")
```

## Current output

```
Before Simulation: These should match 0.8161302208900452, 0.8161302208900452
After Simulation: These should match: 0.033761292695999146, 0.8161302208900452
```
I have tried this with various environments and also the `LightSimBackend`, and the same problem persists. I also checked that `new_sim.current_obs.a_or` matches with `sim.current_obs.a_or`, which is what led me to believe that the thermal limits are being tampered with. Any help on this would be much appreciated.

**Comment by BDonnot** [comment]
Hello,

I will have a look at this asap. Which might not be this week unfortunately

In the mean time, a possible solution might be to use the lightsim2grid backend (which I strongly recommend using because it will be much faster)

Thanks for raising this issue.
