### ISSUE TITLE
Issue when creating a gif

### ISSUE THREAD

**Issue by AvisP** [rte-france/Grid2Op#396]
## Environment
 - Grid2op version: `1.8.1`
 - System: `Mac osx`

## Bug description
When trying to use the create gif option, there is an error in the resizing of the image array. I am getting the following error

```
Saving the gif of the episodes
Creating 0000.gif
Traceback (most recent call last):
  File "/..../Demo Notebooks/DeepQSimpleTrain.py", line 51, in <module>
    res = evaluate(env,
  File "/..../venvs/L2PRN/lib/python3.10/site-packages/l2rpn_baselines/DeepQSimple/evaluate.py", line 184, in evaluate
    save_log_gif(logs_path, res)
  File "/....../L2PRN/lib/python3.10/site-packages/l2rpn_baselines/utils/save_log_gif.py", line 45, in save_log_gif
    ep_replay.replay_episode(episode_id=chron_name, gif_name=gif_name, display=False)
  File "/...../venvs/L2PRN/lib/python3.10/site-packages/grid2op/Episode/EpisodeReplay.py", line 175, in replay_episode
    frames.append(plot_runner.convert_figure_to_numpy_HWC(figure))
  File "/...../venvs/L2PRN/lib/python3.10/site-packages/grid2op/PlotGrid/PlotMatplot.py", line 323, in convert_figure_to_numpy_HWC
    img_arr = np.reshape(img_arr, (h, w, 4))
  File "<__array_function__ internals>", line 180, in reshape
  File "/....../venvs/L2PRN/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 298, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/....../venvs/L2PRN/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc
    return bound(*args, **kwds)
ValueError: cannot reshape array of size 14745600 into shape (720,1280,4)
```

## How to reproduce
The following code can be used to reproduce the issue

```
import grid2op
from grid2op.Reward import L2RPNReward
from l2rpn_baselines.utils import TrainingParam, NNParam
from l2rpn_baselines.DeepQSimple import train
from lightsim2grid.lightSimBackend import LightSimBackend

bk_cls = LightSimBackend

# define the environment
env = grid2op.make("l2rpn_case14_sandbox",
                    reward_class=L2RPNReward,
                    backend=bk_cls())
# use the default training parameters
tp = TrainingParam()
# this will be the list of what part of the observation I want to keep
# more information on https://grid2op.readthedocs.io/en/latest/observation.html#main-observation-attributes
li_attr_obs_X = ["day_of_week", "hour_of_day", "minute_of_hour", "prod_p", "prod_v", "load_p", "load_q",
                    "actual_dispatch", "target_dispatch", "topo_vect", "time_before_cooldown_line",
                    "time_before_cooldown_sub", "rho", "timestep_overflow", "line_status"]
# neural network architecture
observation_size = NNParam.get_obs_size(env, li_attr_obs_X)
# sizes = [800, 800, 800, 494, 494, 494]  # sizes of each hidden layers
sizes = [100, 100, 100]
kwargs_archi = {'observation_size': observation_size,
                'sizes': sizes,
                'activs': ["relu" for _ in sizes],  # all relu activation function
                "list_attr_obs": li_attr_obs_X}
# select some part of the action
# more information at https://grid2op.readthedocs.io/en/latest/converter.html#grid2op.Converter.IdToAct.init_converter
kwargs_converters = {"all_actions": None,
                        "set_line_status": True,
                        "change_bus_vect": True,
                        "set_topo_vect": True
                        }
# define the name of the model
nm_ = "Case14_DeepQSimple"
try:
    train(env,
            name=nm_,
            iterations=10000,
            save_path="./save/DeepQSimple",
            load_path=None,
            logs_dir="./logs/DeepQSimple",
            training_param=tp,
            kwargs_converters=kwargs_converters,
            kwargs_archi=kwargs_archi)
finally:
    env.close()

from l2rpn_baselines.DeepQSimple import evaluate
res = evaluate(env,
                name=nm_,
                load_path="./save/DeepQSimple/", 
                nb_episode=3,
                logs_path="./logs/DeepQSimple",
                nb_process=1,
                max_steps=-1,
                verbose=True,
                save_gif=True)
```
I can see the first time instant show up in a well resolution image, but it is the array reshaping where the issue is happening.....

**Comment by BDonnot** [comment]
Oh great 😊

I planned on looking at it "at some point" but now that there is a fix I'll make sure to include it in the next release.

Thanks a lot!

**Comment by BDonnot** [comment]
On that, note that the model you are trying to use is deprecated, we will not fix anything related to it in l2rpn baselines.

You can use model from ray[rllib] or stable baselines if you prefer. Some examples are available there (*eg* PPOSB3 or PPORllib)

**Comment by AvisP** [comment]
> Oh great 😊
> 
> I planned on looking at it "at some point" but now that there is a fix I'll make sure to include it in the next release.
> 
> Thanks a lot!

No probs!

**Comment by AvisP** [comment]
> On that, note that the model you are trying to use is deprecated, we will not fix anything related to it in l2rpn baselines.
> 
> You can use model from ray[rllib] or stable baselines if you prefer. Some examples are available there (_eg_ PPOSB3 or PPORllib)

Yes I saw that the repo is deprecated. Where can I find the latest repo of models? Based on this I thought it contained the top performing algos from various competitions https://l2rpn-baselines.readthedocs.io/en/latest/external_contributions.html

I am trying to train a model and evaluate its performance. Where can I find the repo of latest algorithms?

**Comment by BDonnot** [comment]
You can use PPO algorithm in ray/rllib here https://l2rpn-baselines.readthedocs.io/en/latest/ppo_rllib.html
Or PPO in stable baselines here https://l2rpn-baselines.readthedocs.io/en/latest/ppo_stable_baselines.html

Or you can have a look at the code there and 2 lines of code you can switch from a PPO to a DQN or SAC or (I guess) any other models supported by the platform of your choice.

Let me know if you want a "sketch" of an example (oe a piece of code that is not tested, might not directly work but is a leap in the right direction and explain what I imagine)

**Comment by AvisP** [comment]
Thanks, I managed to execute the code for PPO_RLLIB, but need to train it longer for better performance. 

Yes you got it right...  please if you can provide a sketch that would be great!

Also I had a follow up question on how to create custom power network models in grid2ops. I was wondering if we can communicate by email on that rather than over here....

**Comment by BDonnot** [comment]
Yes sure, feel free to contact me at my professional address : benjamin.donnot@rte-france.com 😊

As for the code example, I'll do it Monday 😊

**Comment by BDonnot** [comment]
Sorry for the delay in the "code example" I totally forgot.

Basically (I don't like it but that's the way it is for now...) you copy paste the code here https://github.com/rte-france/l2rpn-baselines/blob/c1e2d3616f38a532f327ee85eaa9c0338552ed72/l2rpn_baselines/PPO_SB3/train.py#L39 

Once done, you modify the calls to SB3Agent here https://github.com/rte-france/l2rpn-baselines/blob/c1e2d3616f38a532f327ee85eaa9c0338552ed72/l2rpn_baselines/PPO_SB3/train.py#L293 and there https://github.com/rte-france/l2rpn-baselines/blob/c1e2d3616f38a532f327ee85eaa9c0338552ed72/l2rpn_baselines/PPO_SB3/train.py#L299 by adding:

```python
        agent = SB3Agent(env.action_space,
                         env_gym.action_space,
                         env_gym.observation_space,
                         nn_kwargs=nn_kwargs,
nn_type=SAC,    # ADDED
        )
    else:        
        agent = SB3Agent(env.action_space,
                         env_gym.action_space,
                         env_gym.observation_space,
                         nn_path=os.path.join(load_path, name),
nn_type=SAC,  # ADDED
        )
```

where SAC is (for example)

```python
from stable_baselines3 import SAC
``` 

And that's it.

Of course, the best would be, in the "train" function to have the "nn_type" passed as argument so that you can modify it without having to copy paste...

And the best of the best would be to change the name of the kwargs from "nn_type" to "rl_algorithm" or something because this kwargs has absolutely nothing to do with a neural network, but everything to do with an algorithm to train a policy.

**Comment by BDonnot** [comment]
And to get back to the original question, I think the issue only arises in macos and I don't have a macos machine.

So I will suppose that your fix is correct and modify the code (this looks harmless). I added a basic test for this, but this test pass even without the fix so...
