### ISSUE TITLE
Retrieving the forecast

### ISSUE THREAD

**Issue by pwdemars** [rte-france/Grid2Op#40]
It would be good to have the ability to access the approximate forecast for the next step time step. This is possible at the moment by using `obs.simulate(act)` and viewing attributes of the observation, but it would be great if this was more accessible!

**Comment by BDonnot** [comment]
Hello Patrick

This would indeed be a nice idea. I will work on this on a future version of the package (0.5.9 or 0.6.0, not sure about the number i'll give to the next version).

I didn't had the opportunity to integrate it in this last release (0.5.8) which i wanted to release today for other people to start using new features, especially regarding the voltage control.

So basically i have not forgotten ;-)

Benjamin

**Comment by BDonnot** [comment]
Hello Patrick,

This is to let you know that this feature has been integrated in the coming 0.8.2 version of grid2op. It will be possible to retrieve the injection forecasted at the next time step without running an expense "simlate" with:
```python
prod_p_f, prod_v_f, load_p_f, load_q_f = obs.get_forecasted_inj()
```

I'm closing the issue and thank you for your suggestion

Best

Benjamin
