### ISSUE TITLE
How to get the data time stamp information from EpisodeData

### ISSUE THREAD

**Issue by AvisP** [rte-france/Grid2Op#404]
## Environment
 - Grid2op version: `1.8.1`
 - System: `mac osx`

## Bug description
I would like to get the date, time stamp information from the EpisodeData and EpisodeReplay. But I couldn't manage to figure out how to retrieve it and I do remember seeing somewhere there was a specific function for it. Sample log files if needed are [here](https://easyupload.io/hlp1gv)

## How to reproduce
Currently the code I have now is the following

```
from grid2op.Episode import EpisodeData, EpisodeReplay

# runner_save_path = "./runner_logs/PPO_SB3"
path_agent = "./runner_logs/PPO_SB3" # path to a directory where a runner has been saved
# I study only the first episode saved, because... why not
li_episode = EpisodeData.list_episode(path_agent)
full_path, episode_studied = li_episode[3]
this_episode = EpisodeData.from_disk(full_path, episode_studied)

#General information about the episode
print(this_episode.meta)
```

Any suggestions on how to retrieve date and time stamp information form `this_episode` would be helpful.

**Comment by BDonnot** [comment]
Hello,

I think you get access to the observation if you use the EpisodeData class (see relevant notebook).

And you have a method of the observation to get the datetime if you want. See the dicumentation here for more information https://grid2op.readthedocs.io/en/latest/observation.html#main-observation-attributes
And https://grid2op.readthedocs.io/en/latest/observation.html#grid2op.Observation.BaseObservation.get_time_stamp

I hope this answers the question 😊

**Comment by AvisP** [comment]
Hi Benjamin,

Thanks, I was able to print out the date and time in the following lines

```
for i, obs in enumerate(this_episode.observations):
    print("At step {} day {} month {} year {} hour {} minute {}".format(i, obs.day, obs.month, obs.year, obs.hour_of_day, obs.minute_of_hour))
    print("At step {} using function {}".format(i, obs.get_time_stamp()))
```
