### ISSUE TITLE
Rename "alerts_info.json" into "alarms_info.json" for zonal alarms in ICAPS

### ISSUE THREAD

**Issue by laure-crochepierre** [rte-france/Grid2Op#441]
## Is your feature request related to a problem? Please describe.
In the ICAPS environement, the file describing the alarms is named "alerts_info.json". To be consistent, we should rename it  "alarms_info.json".

## Describe the solution you'd like

- [ ] Rename the file into  "alarms_info.json" in ICAPS env (also in data_test folders "l2rpn_neurips_2020_track1_with_alarm" and "l2rpn_icaps_2021_small_test")
- [ ] Change the variable ALARM_FILE_NAME value in BaseEnv.py 

Ex. This is how i would like it to be done:
```python
ALARM_FILE_NAME = "alarms_info.json"
```

## Additional context
This feature request is for code cleaning for ICAPS environment.

**Comment by BDonnot** [comment]
I think it has been done, no ?

If not do not hesitate to open this issue again.
