### ISSUE TITLE
Put an edge on from disconnected buses to its substation on observation's element graph 

### ISSUE THREAD

**Issue by EloyAnguiano** [rte-france/Grid2Op#456]
## Description

![graph](https://github.com/rte-france/Grid2Op/assets/17010375/3fa7c159-713f-48a1-8740-1330390eb291)

In the image above, there is a particularity of the `element_graph` (created from issue #334 ) that jumps out at first sight, and that is that there are a few bus nodes (in red) that are disconnected from the graph. These buses actually do have topological location, although they are disconnected. Therefore, I think that the correct thing to do would be to put an edge between them and the corresponding substation, but taking advantage of the attribute "connected" (setting it to False) that exists on each node.

This way there would be a way to infer which bus belongs to which substation only looking and graph topology and attributes.

**Comment by BDonnot** [comment]
done and merged in version 1.9.0
