### ISSUE TITLE
Silence the warning and to check from pandapower side

### ISSUE THREAD

**Issue by KishanGitASU** [rte-france/Grid2Op#46]
Encountered the following warnings while running the python notebook "0_basic_functionalities.ipynb". I was using Grid2Op (0.5.7 version).

"**RuntimeWarning: Invalid value encountered in true_divide**"

**Comment by BDonnot** [comment]
Hello,

I did silence this kind of warning in the latest version. Can you check again and close the issue if this solves the problem ?

Thanks

Benjamin

**Comment by KishanGitASU** [comment]
HI, the issue is resolved.
