### ISSUE TITLE
Not able to use make_from_dataset_path with LightSimBackend

### ISSUE THREAD

**Issue by AvisP** [rte-france/Grid2Op#500]
I am trying to make an environment from a custom path location using `make_from_dataset_path` but it is giving some errors when using LIghtSimBackend. When I am running the following code snippet

``` 
import grid2op
from lightsim2grid import LightSimBackend 
from grid2op.Reward import LinesCapacityReward 

env = grid2op.make_from_dataset_path(dataset_path="/custom_path/l2rpn_case14_sandbox", 
                        reward_class=CustomReward,
                        backend=LightSimBackend)

```

I get the error 

```
Traceback (most recent call last):
  File "/Users/...../env_setup.py", line 5, in <module>
    env = grid2op.make_from_dataset_path(dataset_path="/Users/paula/data_grid2op/l2rpn_case14_sandbox_train", 
  File "/Users/..../lib/python3.10/site-packages/grid2op/MakeEnv/MakeFromPath.py", line 381, in make_from_dataset_path
    backend = _get_default_aux(
  File "/Users/..../lib/python3.10/site-packages/grid2op/MakeEnv/get_default_aux.py", line 140, in _get_default_aux
    raise EnvError(msg_error)
grid2op.Exceptions.EnvExceptions.EnvError: Grid2OpException EnvError "The backend of the environment (keyword "backend") must be an instance of grid2op.Backend"
```
I think it is related to LightSimBackend class missing under grid2op.Backend. However it works fine without mentioning the backend class which default to PandapowerBackend. Also I should mention that in the `config.py` of the custom environment I had to change `"backend"` to `"backend_class"`. Any help or workaround would be appreciated, thanks!

**Comment by BDonnot** [comment]
Hello,

Help can be found pretty much everywhere on the documentation, the starting kit and even on the error message or even better, on the readme of lightsim2grid...

# readme of lightsim2grid

https://github.com/BDonnot/lightsim2grid#1-as-a-grid2op-backend-preferred-method

```python
import grid2op
from lightsim2grid import LightSimBackend
env_name = "l2rpn_case14_sandbox"  # or any other name.
env = grid2op.make(env_name, backend=LightSimBackend())

# do regular computation as you would with grid2op
```

# Error message

> "The backend of the environment (keyword "backend") must be an instance of grid2op.Backend"

You provided `backend=LightSimBackend`, and if you type `type(LightSimBackend)` you'll see it's... a class and not an object of a class. Create an object of type `LightSimBackend` (*eg* `backend=LightSimBackend()`) and then pass it to the make function or even better, create the object in the make call : `make(..., backend=LightSimBackend())`

# starting kit

Grid2op comes with a lot of notebook (some might be out dated but still...) and in this one https://colab.research.google.com/github/rte-france/Grid2Op/blob/master/getting_started/11_IntegrationWithExistingRLFrameworks.ipynb (last one) you can find:

```python
import grid2op
try:
    from lightsim2grid import LightSimBackend
    bk_cls = LightSimBackend
except ImportError as exc:
    print(f"Error: {exc} when importing faster LightSimBackend")
    from grid2op.Backend import PandaPowerBackend
    bk_cls = PandaPowerBackend
    
env_name = "l2rpn_case14_sandbox"
env_glop = grid2op.make(env_name, test=True, backend=bk_cls())
```
# documentation

See here:
https://grid2op.readthedocs.io/en/latest/gym.html#python-complains-about-pickle

(it's not straightforward, but i simply typed "backend=" in the search bar and went through all the results one by one until i found an example, took me maybe 1 or 2 minutes)

```python
from grid2op import make
from grid2op.Reward import RedispReward
from lightsim2grid import LightSimBackend

env_name = 'l2rpn_wcci_2022'
backend_class = LightSimBackend
env = make(env_name, reward_class=RedispReward, backend=backend_class())
```


So my question, were have looked at to fail to find this information ? How to make it clearer where to find it ?
