### ISSUE TITLE
Missing reference to AlertAgent in Agent/__init__.py

### ISSUE THREAD

**Issue by marota** [rte-france/Grid2Op#507]
## Environment
 - Grid2op version: `0.x.x`
 - System: `windows, osx, ubuntu16.04, ...`
 - Additional system information

### Command line

```bash
# command line used if any 
```

### Code snippet

```python
import grid2op

... # Some code 
```

## Current output

```
The output of the code snippet above
```

## Expected output

```
The expected output and/or expected behavior description
```

**Comment by BDonnot** [comment]
In the mean time you can use `from grid2op.Agent.alertAgent import AlertAgent`
