### ISSUE TITLE
Isolating load issue

### ISSUE THREAD

**Issue by sunghoonhong** [rte-france/Grid2Op#51]
I played with “case5_example” environment, and I found a strange situation.
Initially, all loads, generators, and powerlines are connected to bus1. If I change bus of a load, which means change bus connection 1 to 2, the load is isolated, and therefore, I think it must lead to the game over. However, the game was not over. I changed the bus of two loads, and the game still was not over (‘done’ keeps giving ‘false’). Is it legal action or bug?
![image](https://user-images.githubusercontent.com/39590258/78025650-59139b80-7395-11ea-9745-d338bdd04c3e.png)

If I try to change the bus of last load, I found
>{'disc_lines': array([False, False, False, False, False, False, False, False]), 'is_illegal': False, 'is_ambiguous': False, 'is_dispatching_illegal': True, 'is_illegal_reco': False, 'exception': [Grid2OpException Grid2OpException('Impossible to solve for this equilibrium, not enough production')]}

from ‘info’. After this step, all actions did not work, but ‘done’ gave ‘false’.

Best regards,
Thank you

**Comment by BDonnot** [comment]
Dear Sunghoon,

Thanks for raising this error. Indeed it is a bug in the implementation of pandapower backend. I fixed the issue.
The fix will be live in next version (0.5.9 or 0.6.0).
I also made a test to make sure this issue will not arise again.

Thanks a lot

Benjamin

**Comment by sunghoonhong** [comment]
Thanks for your reply.

I'm looking forward to checking new version!

**Comment by BDonnot** [comment]
I will close this issue when the new version will be released :-)

Have a nice day

Benjamin

**Comment by BDonnot** [comment]
The new release is out. I am closing this issue.

Don't hesitate to open it again if the new versions did not fix this bug.

Best

Benjamin
