### ISSUE TITLE
Illegal to Change Topology at more than 1 Substation

### ISSUE THREAD

**Issue by DEUCE1957** [rte-france/Grid2Op#517]
## Documentation issue description
When calling change_bus on elements from different substations, the action is replaced with DoNothing, since changing elements at multiple substations at once is Illegal. 

This is a documentation problem, as I cannot find any discussion of this in the Grid2Op Docs. The same restriction appears to apply to all standard Grid2Op environments. Why can we not change the topology at multiple substations at the same time? We would like our agent to be able to make many decisions in parallel. 

Suggest adding some documentation under IllegalAction clarifying this.

## Additional context
<img src="https://i.imgur.com/W1BPniS.png">

**Comment by BDonnot** [comment]
Hello

Thanks for raising this documentation issue. I'll try to make it clearer.

In the mean time, you can have a look at the first notebook here https://github.com/rte-france/Grid2Op/blob/master/getting_started/00_Introduction.ipynb that details a bit why we took this decision.

And if you want to "get rid" of this operational constraints, you can change the parameters of your environment with:

```python
env = ...  # whatever environment
param = env.parameters
param.MAX_SUB_CHANGED = 99999
param.MAX_LINE_STATUS_CHANGED = 99999
env.change_parameters(param)
env.change_forecast_parameters(param)

# and don't forget to reset
obs = env.reset()
````

**Comment by BDonnot** [comment]
Is this solution working for you ?

**Comment by BDonnot** [comment]
I close this issue as you appear to have been satisfied with my previous answer. If that is not the case then feel free to re open it.
