### ISSUE TITLE
env.seed(n) has no effect

### ISSUE THREAD

**Issue by EricavanderSar** [rte-france/Grid2Op#519]
## Environment
 - Grid2op version: `1.9.1`
 - System: `mac os`
 - Additional system information

## Bug description
Using different values for n in  env.seed(n) does not seem to have any effect. When I change the seed but use the same chronics  all results and observation values seem to be the same.
Maybe my expectation is off, but I expected that within each chronic there would be a small variance. 
Furthermore, the documentation says: 
Set the seed of this :class:`Environment` for a better control and to ease reproducible experiments.

So I expected therefore not using this or changing the value of the seed would change the output for the experiments.

## How to reproduce

Test the following code for multiple values of _n_ and you will get the same result each time.

### Code snippet

```python

import grid2op
from tqdm.notebook import tqdm  # for easy progress bar
display_tqdm = True  # this is set to False for ease with the unitt test, feel free to set it to True
from grid2op.PlotGrid import PlotMatplot
from grid2op.Agent import DoNothingAgent
env = grid2op.make("rte_case5_example", test=True)
my_agent = DoNothingAgent(env.action_space)

n =20
env.seed(n)
env.set_id(5)
my_agent = DoNothingAgent(env.action_space)
all_obs = []
obs = env.reset()
all_obs.append(obs)
reward = env.reward_range[0]
done = False
nb_step = 0
with tqdm(total=env.chronics_handler.max_timestep(), disable=not display_tqdm) as pbar:
    while True:
        action = my_agent.act(obs, reward, done)
        print(obs.load_p)
        obs, reward, done, _ = env.step(action)
        pbar.update(1)
        if done:
            break
        all_obs.append(obs)
        nb_step += 1

```

## Current output
Same output for each n

## Expected output
Different output for each n.

Side note: perhaps my expectation is just off, but I discussed this also with other people and we all expected the seed to have an influence on the behaviour of the environment. It is not really a big bug, but it is not as expected.

**Comment by BDonnot** [comment]
Hello,

This is perfectly normal as this environment is not stochastic (no hazards, no maintenance, no opponent, no noise in the observation etc).

This will not be the case if:
- you use noise in the Observation https://grid2op.readthedocs.io/en/latest/observation.html#grid2op.Observation.NoisyObservation
- if you set up an opponent https://grid2op.readthedocs.io/en/latest/opponent.html
- if you generate time series "on the fly" https://grid2op.readthedocs.io/en/latest/chronics.html#grid2op.Chronics.FromChronix2grid
- if you use maintenance https://grid2op.readthedocs.io/en/latest/chronics.html#grid2op.Chronics.GridStateFromFileWithForecastsWithMaintenance
- if you generate noisy forecasts https://grid2op.readthedocs.io/en/latest/timeserie_handlers.html#grid2op.Chronics.handlers.NoisyForecastHandler

And probably many other ways.

Also if you use a "regular" environment and not some really basic one mainly here for demonstration or education purpose.

Hope that helps

Benjamin

**Comment by EricavanderSar** [comment]
Hello Benjamin,

That helps indeed. Now it is more clear what en when I should expect something from setting the seed of the environment.
Thank you for your quick reply! 

Best,
Erica

**Comment by EricavanderSar** [comment]
Just to get back on your last comment:
" Also if you use a "regular" environment and not some really basic one mainly here for demonstration or education purpose" 

I also tested it on l2rpn_case14_sandbox, but this environment also doesnt have any maintenance or opponnent.
So, just to be clear: When I would test it on any of the environments that DO include maintenance / opponents you expect the seed will be of influence, right?

Thank you again,
Erica

**Comment by BDonnot** [comment]
Yes if the environment you're using used one of the things I mentioned in my previous message, to get reproducible experiments you need to set the seed.
This is case for most environment with 30 substations or more.

**Comment by EricavanderSar** [comment]
Clear! Thank you Benjamin.
