### ISSUE TITLE
How to define path_save in grid2op.make?

### ISSUE THREAD

**Issue by jhmenke** [rte-france/Grid2Op#52]
I am using the *grid2op.make* function to generator a runner with an environment. How is it possible to define the path where the logs are saved in this function?

**Comment by BDonnot** [comment]
Hello

As explained in the notebook 0 (last few cells) you can do it this way:

```python
import grid2op
from grid2op.Runner import Runner
env = grid2op.make()
runner = Runner(**env_case14.get_params_for_runner())
```
Once your runner is initialized, you can use it to compute any number of scenarios that you want, with what is explained in notebook 4:
```python
res = runner.run(path_save="THEPATH\HERE",
    nb_episode=2,   # number of episode to run, any positive integer
    max_iter=100  # maximum number of steps per episode, any positive integer
)
```

Sorry if the stuff are not properly organized

Benjamin

**Comment by jhmenke** [comment]
Thanks. It works like this:

```
env = grid2op.make(...)
runner = Runner(**env.get_params_for_runner(), agentClass=customAgent)
res = runner.run(path_save="customAgentLogs", nb_episode=1, max_iter=1000, pbar=True)
```
