### ISSUE TITLE
Dangerous case sensitive filenames.

### ISSUE THREAD

**Issue by benedikt-schesch** [rte-france/Grid2Op#523]
## Environment
 - Grid2op version: `a819a77`
 - System: `osx`

## Bug description
File name which only have a case-sensitive distinction are being used, which is very dangerous and does not work correctly on OSX since HFS+ is case insensitive: 
https://discussions.apple.com/thread/251231049

The file that have this problem are:
`grid2op/Action/_backendAction.py` and `grid2op/Action/_BackendAction.py`.

This is very dangerous and prevents OSX based developers to develop this code since these files collide.

**Comment by benedikt-schesch** [comment]
I think this is relatively high priority bc it prevents ppl to work on the project correctly.

**Comment by BDonnot** [comment]
Hello,

I thought this was only a problem on windows based OS and this problem can be solved (for users) by installing the whl python package (which works on all platforms I'm aware of).

This change has been done recently to be more compliant with python naming convention (and to avoid collision python side between the class _BackendAction and the file _BackendAction.py which is also quite terrible...) I did not thought (when making this change) that it would cause another issue. I'll try to think of a better solution that would allow:
1) to be compliant with python naming convention
2) to keep backward compatibility (things like `from grid2op.Action._BaseAction import _BaseAction` should work)
3) does not cause any issue on mac os and windows

If you know one i'm happy to implement it asap.

Thanks for spotting it

Benjamin

**Comment by benedikt-schesch** [comment]
Thanks, I'll close this issue.
