### ISSUE TITLE
chronics_handler path not updated when creating 2 environments in a row

### ISSUE THREAD

**Issue by DEUCE1957** [rte-france/Grid2Op#536]
## Environment
 - Grid2op version: '1.9.5'
 - System: 'Window 11'
 - Python 3.9.7

## Bug description
After using grid2op.make(ENV_NAME, data_feeding_kwargs={}) to create a Grid2Op Environment and then env.train_val_split_random(deep_copy=True) to generate the folders for training, validation and test Environment, if you immediately grid2op.make(ENV_NAME + '_val', data_feeding_kwargs={}) the env path will load correctly, but the chronics handler will still point to the old ENV_NAME's chronics. Consequently the validation environment is not properly isolated from the training and testing environments. This only happens when we pass "data_feeding_kwargs" as a keyword argument to make.

## How to reproduce
```
import grid2op
from pathlib import Path as p
ENV_NAME = "l2rpn_wcci_2022"
env_settings = {"test":False,
                "data_feeding_kwargs":{}
}
env = grid2op.make(ENV_NAME, **env_settings)
if not (p(env.get_path_env()).parent / (ENV_NAME + "_val")).exists():
    env.train_val_split_random(deep_copy=True)
val_env = grid2op.make(ENV_NAME + "_val", **env_settings)
print(val_env.chronics_handler.path)
```
Expected Output: .../l2rpn_wcci_2022_val/chronics
Actual Output: .../l2rpn_wcci_2022/chronics

**Comment by BDonnot** [comment]
I found the origin of the bug, it's caused by using python multable in function (re using the env_settings)...

To solve it (in the short term) you can do:

```python
import grid2op
import copy
from pathlib import Path as p
ENV_NAME = "l2rpn_wcci_2022"
env_settings = {"test":False,
                "data_feeding_kwargs":{}
}
env = grid2op.make(ENV_NAME, **copy.deepcopy(env_settings))
if not (p(env.get_path_env()).parent / (ENV_NAME + "_val")).exists():
    env.train_val_split_random(deep_copy=True)
val_env = grid2op.make(ENV_NAME + "_val", **copy.deepcopy(env_settings))
print(val_env.chronics_handler.path)
```

I'll make the deepcopy inside the make function to avoid these weird behaviour

**Comment by BDonnot** [comment]
And because i'll reference it inside the grid2op, to show another way to do the same things:

```python
import grid2op
from pathlib import Path as p
ENV_NAME = "l2rpn_wcci_2022"
def get_env_settings():
    env_settings = {"test":False,
                "data_feeding_kwargs":{}
    }
    return env_settings
env = grid2op.make(ENV_NAME, **get_env_settings())
if not (p(env.get_path_env()).parent / (ENV_NAME + "_val")).exists():
    env.train_val_split_random(deep_copy=True)
val_env = grid2op.make(ENV_NAME + "_val", **get_env_settings())
print(val_env.chronics_handler.path)
```
