### ISSUE TITLE
EpisodeData to/from disk does not preserve energy graphs

### ISSUE THREAD

**Issue by DEUCE1957** [rte-france/Grid2Op#538]
## Environment
 - Grid2op version: `1.9.5`
 - System: Windows 11
 - Python 3.11.3

## Bug description
When loading a previously completed Episode from_disk using GridOp's EpisodeData class, the observations return an empty energy graph (1 node, no edges). However if we plot the Observation's EnergyGraph before saving to disk (i.e. within the RL loop) it returns a valid energy graph. It seems obs.get_energy_graph() relies on information that is not stored in obs.to_vect() (specifically obs.flow_bus_matrix()).

## How to reproduce
The following code runs a minimum EpisodeData class (without a runner) for 1 timestep on the "rte_case14_realistic" environment, we plot the Energy Graph for the observation before and after saving from disk.
```python
import logging
import grid2op
import numpy as np
import networkx as nx
import matplotlib.pyplot as plt
from grid2op.Episode import EpisodeData
from pathlib import Path as p
env = grid2op.make("rte_case14_realistic")
obs = env.reset()

max_no_of_timesteps = 1

# Make Temporary Path to Store Episode Data in
path_save = p.cwd() / "Temp"
path_save.mkdir(exist_ok=True)

array_names = ("actions", "env_actions", "observations", "attacks", "disc_lines", "rewards", "times")

# Arrays needed to initialize Episode Data class
episode_data_dict = dict( 
    path_save=path_save,
    logger = logging.Logger("Logger"),
    actions = np.full((max_no_of_timesteps, env.action_space.n), fill_value=np.NaN, dtype=np.float16),
    env_actions = np.full((max_no_of_timesteps, env._helper_action_env.n), fill_value=np.NaN, dtype=np.float32),
    observations = np.full((max_no_of_timesteps + 1, len(obs.to_vect())),fill_value=np.NaN,dtype=np.float32),
    rewards = np.full(max_no_of_timesteps, fill_value=np.NaN, dtype=np.float32),
    disc_lines = np.full((max_no_of_timesteps, env.backend.n_line), fill_value=np.NaN, dtype=np.bool_),
    times = np.full(max_no_of_timesteps, fill_value=np.NaN, dtype=np.float32),
    disc_lines_templ = np.full((1, env.backend.n_line), fill_value=False, dtype=np.bool_),
    attack_templ = np.full((1, env._oppSpace.action_space.size()), fill_value=0.0, dtype=np.float32),
    attack = np.full((max_no_of_timesteps, env._opponent_action_space.n), fill_value=0.0, dtype=np.float32),
    legal = np.full(max_no_of_timesteps, fill_value=True, dtype=np.bool_),
    ambiguous = np.full(max_no_of_timesteps, fill_value=False, dtype=np.bool_),
    observation_space=env.observation_space,
    action_space=env.action_space,
    attack_space=env._opponent_action_space,
    helper_action_env=env._helper_action_env,
)
episode_data = EpisodeData(**episode_data_dict)

# Single step of reinforcement learning loop
act = env.action_space() # Do Nothing
obs, reward, done, info = env.step(act)
# Save To Episode Data instance
episode_data.incr_store(obs=obs,
                        efficient_storing=True,
                        time_step=0, 
                        time_step_duration=0.0,
                        reward=reward, 
                        env_act=env._env_modification,
                        act=act, 
                        opp_attack=env._oppSpace.last_attack,
                        info=info
)
# Save Episode data to disk
episode_data.to_disk()

print("Energy Graph before Saving to Disk")
nx.draw(episode_data.observations[0].get_energy_graph())
plt.show()

# Load From Disk
episode_data = EpisodeData.from_disk(path_save, "EpisodeData")
obs = episode_data.observations[0]

print("Energy Graph after loading from Disk")
nx.draw(obs.get_energy_graph())
plt.show()
```

**Comment by BDonnot** [comment]
Hello,

I'm not sure this is the intended usage of this class. Indeed, you first need to create and store the data using the `Runner` class.

And then load hem as you do. There are some tricks that prevents you to initialize EpisodeData this way if I remember correctly. Feel free to consult the documentation here https://grid2op.readthedocs.io/en/latest/chronics.html#grid2op.Chronics.FromOneEpisodeData

I'll investigate it with the standard use and keep you updated.

**Comment by DEUCE1957** [comment]
> Hello,
> 
> I'm not sure this is the intended usage of this class. Indeed, you first need to create and store the data using the `Runner` class.
> 
> And then load hem as you do. There are some tricks that prevents you to initialize EpisodeData this way if I remember correctly. Feel free to consult the documentation here https://grid2op.readthedocs.io/en/latest/chronics.html#grid2op.Chronics.FromOneEpisodeData
> 
> I'll investigate it with the standard use and keep you updated.

You are right this is not the correct / official way to work with EpisodeData, since that should be done through the Runner class. In my case I needed a bit more control over the RL loop, but still want the ability to replay / visualize the performance of the agents. I ended up rewriting the EpisodeData class so that it generates fewer files on my harddisk (a single .npz file instead of several), is that something I should send a pull request for?  

I see that you commited a fix for this, thank you :)

**Comment by BDonnot** [comment]
Hello,

Yes there were still a slight bug (a flag that was not set correctly) that indeed I fixed.

If you have a   `ConciseEpisodeData` or something alike (something that behaves like an episode data but with different storage, such as one file for all, or a database or anything else) then yes for sure I'd be glad to review a pull request 😊

Thanks
