### ISSUE TITLE
ChronicsError: Grid2OpException ChronicsError "Path "c:\users\username\miniconda3\envs\grid2op\lib\site-packages\grid2op\data\test_multi_chronics" doesn't exists."

### ISSUE THREAD

**Issue by KishanGitASU** [rte-france/Grid2Op#55]
I had to reinstall everything for the setup I had for Grid2Op. I am using windows machine.

I ran the basic functionality ipynb and got the above error. I made sure the virtual environment is added as the kernel for the jupyter notebook. The problem is that my git pull saved all the downloaded code from github repo  to my D drive  and the missing folder in the above error is located at the following location i.e., D:\Grid2Op\grid2op\data\test_multi_chronics. However, when I do "pip install -U ." in the grid2op folder, the grid2op package is installed in my C drive where miniconda libraries folder is present as a package. When it installs, it does not copy the data folder (from my D drive) to the package installed location (C drive).

To run basic functionality ipynb without error, I had to manually copy the "data" folder from D drive to the desired location in C drive. I am running the virtual environment from my Grid2Op folder and call jupyter notebook from there.

**Comment by Tezirg** [comment]
Hello Kishan, thank you for reporting the issue.

We will discuss internally whether we should ship the dataset samples inside the grid2op package or leave it as is. That would increase the size of the package by ~7.9MB. 

Meanwhile, for your needs you could try to use `pip install -e .`  which should link the package in edit mode to the root of Grid2Op and therefore include the data folder.

**Comment by Tezirg** [comment]
Hello again Kishan,

After discussion we concluded that shipping datasets samples in the grid2op package is not a suitable solution. 

As you can see in the notebook (cell 3): 
```python
multi_episode_path = grid2op.CHRONICS_MLUTIEPISODE
```
Is given to the `ChronicsHandler` (cell 4):
```python
data_feeding = ChronicsHandler(chronicsClass=Multifolder,
                               path=multi_episode_path,
                               gridvalueClass=GridStateFromFileWithForecasts,
                               max_iter=max_iter)
```

So you should be able to edit cell 3 so that:
```python
multi_episode_path = "D:\Grid2Op\grid2op\data\test_multi_chronics"
```
And everything should work as expected.
