### ISSUE TITLE
Ability to pass custom load and solar patterns in generate_data function

### ISSUE THREAD

**Issue by swaroopguggilam** [rte-france/Grid2Op#553]
As we discussed over the Discord,

## Current Behavior
If we use the grid2op environment to access chronix2grid to generate chronics, it uses the default patterns that come with chronix2grid, such as load or solar patterns (I believe it is French data).

## Feature Request
It would be great if there were an easy way to pass custom patterns (file locations) from grid2op. I am not sure if it should be passed as an argument for the generate_data function or may be part of the config file.

## Additional Notes
I believe chronix2grid does have the parameters to specify the locations of these patterns and pass it to its functions; the effort might be to enable that in the grid2op environment/wrapper that is accessing chronix2grid.

I will try it, but I thought to put this here for the records.

**Comment by BDonnot** [comment]
Hello,

From what I see, the function (for recent grid2op version) accepts a "kwargs" argument, so it should be "ok" from a grid2op perspective. WHat needs to be changed is the chronix2grid function `add_data` (`from chronix2grid.grid2op_utils import add_data`)

I just write this here to tell you i did not forget this, just that I don't have the time to work on this at the moment :-(

**Comment by BDonnot** [comment]
Hello,

In case this is still relevant, I made it available in chronix2grid `add_data` function. For now it is not released yet (waiting for a review before merging) but you can already use it if you install chronix2grid from source with:

> pip install git+https://github.com/bdonnot/chronix2grid.git@bd-dev

I put it somewhere in the doc of chronix2grid but basically :

```
    load_weekly_pattern: pd.DataFrame
        The pattern used as a reference to generate the loads.
        
        It sould be a dataframe with 2 columns: `datetime` and `test`.
        
        In the first column (`datetime`) you should have time stamp (format "%Y-%m-%d %H:%M:%S" 
        *eg* `2017-01-07 23:55:00`). The second oui should have a number "approximately one" which
        gives the relative ratio of demand for the whole grid at this time stamp.
        
        We only tested this when the data was given at 5 minutes resolution (two consecutive rows are 
        distant from 5 minutes) and with the equivalent of 2 years of data. It might work
        (or not) in other cases...
        
```

To use it just install chronix2grid (provided that it's already set up on your machine) and then you can use (without having to change grid2op) with:

```python
seed = ...
load_weekly_pattern_new = ... (see doc for format...)
env.generate_data(nb_year=1, load_weekly_pattern=load_weekly_pattern_new,  seed=seed, ...)
```

**Comment by swaroopguggilam** [comment]
Thank you very much. Yes, this is still relevant and timely.
