### ISSUE TITLE
Plot_helper request: add option to see flows in Amps and MW

### ISSUE THREAD

**Issue by marota** [rte-france/Grid2Op#57]
For now with from the plotly helper (from grid2op.Plot import PlotPlotly) we can only see the flow usage rate in %. It would be nice to be able to see it in Amperes or MW as well.

**Comment by Tezirg** [comment]
This feature has been added in `0.7.0`:

You can now specify the type of information you wish to see on powerlines, loads and generators.
```python
plotter_instance.plot_obs(the_observation,
                          line_info="rho", # Oneof ["rho", "p", "a", "v"]
                          load_info="p", # Oneof ["p", "v"]
                          gen_info="p") # Oneof ["p", "v"]
```
This is supported for all Plotter implementations as well. (PyGame, MatPlotlib and Plotly)
