### ISSUE TITLE
Codalab scoring throws an error when filtering chronics

### ISSUE THREAD

**Issue by EloyAnguiano** [rte-france/Grid2Op#590]
## Environment
 - Grid2op version: `1.9.5`
 - System: Ubuntu 20.04
 - Python: 3.10.13

## Bug description
I am trying to make a callback as they do in SB3 for getting the codalab score at distinct timesteps. As my training and testing chronics differ, I am trying to filter the train chronics to only use the test ones at that callback. I haver realised that if you put a filter to the chronics and it is not the first one (the `00` at `rte_case5_step`) it returns an error. 

Checking the code it seems to be an assumption of the order when it comes to make the `nb_scenario` loop at initialization.

## How to reproduce
```python
import grid2op
from grid2op.utils import ScoreL2RPN2020
from grid2op.Agent import DoNothingAgent
import re


def create_filter(pattern):
    return lambda path: re.match(pattern, path)


env = grid2op.make("rte_case5_example", test=True)
ch_patterns = env.chronics_handler.reset()
ch_patterns = ch_patterns.tolist()

ch_filters = list(map(create_filter, ch_patterns))
ch_filters = ch_filters[17:19]  # Just getting score of 17 to 19 chronics

nb_scenario = 2
agent = DoNothingAgent(env.action_space)
for f in ch_filters:
    handler = env.chronics_handler
    handler.set_filter(f)
    chronics = handler.reset()
    full_chronic_name = chronics[0]
    chronic_name = full_chronic_name.split("/")[-1]

    scorer_2020 = ScoreL2RPN2020(
        env,
        nb_scenario=nb_scenario,
        env_seeds=[0 for _ in range(nb_scenario)],
        agent_seeds=[0 for _ in range(nb_scenario)],
    )

    score_2020 = scorer_2020.get(agent)

    print(score_2020.get(agent))

```

## Current output
```
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpra4i6_5_/00/episode_meta.json'
```

**Comment by BDonnot** [comment]
Hello,

Indeed I did not think about this combined usage of "filter" and "evaluation".

The workflow I had in mind to achieve what (I think) you want to achieve is to split the environment between train / val and test environments (using for example https://grid2op.readthedocs.io/en/latest/environment.html#splitting-into-raining-validation-test-scenarios ) and then run the evaluation on the validation (or test) environment only, running all the time series there (with always the same seed)

Would that solve your problem ?

**Comment by BDonnot** [comment]
(also please note that upgrading grid2op might solve your issue. You are 4 or 5 version behind the most recent one and there has been more than a dozen of critical fixes I would guess, so first maybe try to upgrade :-) )

**Comment by BDonnot** [comment]
After further investigation and dive deep into your code what you do is evaluate the environment 4 times, 2 times on each "time series" instead of evaluating it one time per time serie you want to study.

The best solution (by far, much much less error prone !) is to split your overall environment into train / val and test and then at evaluation time use the validation or test environment.

The second best alternative, is to create the "test environment" in your script, like this (adapted from the example above) and then to run it:

```python
import grid2op
import os
from grid2op.utils import ScoreL2RPN2020
from grid2op.Agent import DoNothingAgent

test_env = grid2op.make("rte_case5_example", test=True)
ch_patterns = test_env.chronics_handler.reset()
ch_patterns = ch_patterns.tolist()
ch_patterns = ch_patterns[17:19]

nb_scenario = len(ch_patterns)
agent = DoNothingAgent(test_env.action_space)
handler = test_env.chronics_handler
handler.set_filter(lambda path: path in ch_patterns)
chronics = handler.reset()
# it's only at this stage that "test_env" is a proper testing environment, provided
# that you did not train on it

scorer_2020 = ScoreL2RPN2020(
    test_env,
    nb_scenario=nb_scenario,
    env_seeds=[0 for _ in range(nb_scenario)],
    agent_seeds=[0 for _ in range(nb_scenario)],
)

score_2020 = scorer_2020.get(agent)
print(score_2020)
for scen_path, score, ts_survived, total_ts in zip(ch_patterns, *score_2020):
    print(f"For scenario {os.path.split(scen_path)[-1]}, agent scores {score} surviving {ts_survived} / {total_ts}")
```
If you really don't want to do that, then simply use `1` instead of `2` in the evaluation (remember here that your "scorer" has an environment with only one time serie, so evaluating twice the agent on it does not make lots of sense), like this:

```python

import grid2op
from grid2op.utils import ScoreL2RPN2020
from grid2op.Agent import DoNothingAgent
import re


def create_filter(pattern):
    return lambda path: re.match(pattern, path)


env = grid2op.make("rte_case5_example", test=True)
ch_patterns = env.chronics_handler.reset()
ch_patterns = ch_patterns.tolist()

ch_filters = list(map(create_filter, ch_patterns))
ch_filters = ch_filters[17:19]  # Just getting score of 17 to 19 chronics

nb_scenario = 2
agent = DoNothingAgent(env.action_space)
for f in ch_filters:
    handler = env.chronics_handler
    handler.set_filter(f)
    chronics = handler.reset()
    full_chronic_name = chronics[0]
    chronic_name = full_chronic_name.split("/")[-1]

    scorer_2020 = ScoreL2RPN2020(
        env,
        nb_scenario=1,
        env_seeds=[0 for _ in range(nb_scenario)],
        agent_seeds=[0 for _ in range(nb_scenario)],
    )

    score_2020 = scorer_2020.get(agent)

    print(score_2020.get(agent))
```

Or better, first you create your test environment by selecting the time series you want to use, then you use the scorer on this whole environment:

**Comment by BDonnot** [comment]
On latest grid2op version both these scripts are working.

> Is it maybe because the grid2op version? Which change at changelog could affect this?

Maybe try to upgrade and then see if it works. Then you can start a dichotomy to know starting from which version it starts to work. Then you look at the changelog of this specific version to know what would be the cause of that.

I can't say more.

**Comment by BDonnot** [comment]
Also, have you look here : https://grid2op.readthedocs.io/en/latest/environment.html#grid2op.Environment.Environment.train_val_split

I think that is doing what you want.

**Comment by EloyAnguiano** [comment]
Upgrading makes me unstable. Checking my unit testing it retrieves:
`AttributeError: 'LightSimBackend_rte_case5_example' object has no attribute '_missing_two_busbars_support_info`'

My previous versions were:
```
    Grid2Op==1.9.5
    LightSim2Grid==0.7.6.dev0
```
But upgrading Grid2Op to 1.10.0 gives me that error whether I have` LightSim2Grid==0.7.6.dev0` or `LightSim2Grid==0.7.5`

Which versions combinations are stable?

**Comment by BDonnot** [comment]
It is considered a good practice in machine learning / statistics to split your data and train only on a subset of them, then tune your hyper parameters on another part and finally when you write a paper or want to publish some results somehow to evaluate on the last bit.

This is exactly what we try to do in the l2rpn compztitios:
- the public training set is available for everyone
- people can do lots of evaluation of their method on the "validation" phase, which should be the step "tune the hyper parameters"
- results are computed only once on the private test set.


We developed the "train / val / split" function for people to mimic this good practice. If you don't want to, no one forces you of course. But it's not a "good practice" for no reason.

This is why your first bullet point is not totally valid. When you train you might have anything you want. But only one training environment.
Then you run the evaluation script only once.

And in all cases, the split should be done before you run anything. So be a pre processing step and not be ran each time you want to train or evaluate an agent.

I will not comment on your second point. You do what is best for your research. Grid2op has not been designed directly for this and probably the way you do does not address your use case.

**Comment by BDonnot** [comment]
Oh, that just reminds me that:

> Simultaneus executions with different assumptions could lead to too much disk usage or collisions.

Is precisely the reasons why I think your scripts does not work. Because internally the scores function are using the hard drive. And i guess the all write on the same spot with the same names on the hard drives.

The "only clean" solution that I see here is to use the `train_val_split` function to generate as many environments as you want (one per scenario) with something like this:

```python
import grid2op
import os
import shutil

nb_env = 3
id_start = 17
env_name = "l2rpn_case14_sandbox"

# create the environment
env = grid2op.make(env_name)

# some constant data
path_env_stored = os.path.split(env.get_path_env())[0]
_name_garbage = "garbagedontuse"

# extract time series names
ch_patterns = env.chronics_handler.reset()
ch_patterns = ch_patterns.tolist()
ch_patterns = ch_patterns[id_start:(id_start+nb_env)]


for time_series_this_env in ch_patterns:
    # extract the "validation" env which is the env with 
    # only one time series
    # NOT a good practice in ML to evaluate and test on same
    # environment !
    ts_this = os.path.split(time_series_this_env)[-1]
    env.train_val_split(val_scen_id=[ts_this],
                        add_for_val=os.path.split(time_series_this_env)[-1],
                        add_for_train=_name_garbage)
    
    # remove the "train" environment that has been created for nothing
    shutil.rmtree(os.path.join(path_env_stored, env_name + "_" + _name_garbage))
  ```

This would be the pre processing step, that you run only once.

Then you can run something like:

```python
import grid2op
import os

nb_env = 3  # same as the pre processing !
id_start = 17  # same as the pre processing !
env_name = "l2rpn_case14_sandbox"

# create the environment
env = grid2op.make(env_name)

# extract time series names
ch_patterns = env.chronics_handler.reset()
ch_patterns = ch_patterns.tolist()
ch_patterns = ch_patterns[id_start:(id_start+nb_env)]


agent = DoNothingAgent(env.action_space)
for time_series_this_env in ch_patterns:
    ts_this = os.path.split(time_series_this_env)[-1]
    test_env = grid2op.make(env_name+"_"+ts_this)

    scorer_2020 = ScoreL2RPN2020(
        test_env,
        nb_scenario=1,
        env_seeds=[0 for _ in range(nb_scenario)],
        agent_seeds=[0 for _ in range(nb_scenario)],
    )

    score_2020 = scorer_2020.get(agent)

    print(score_2020.get(agent))
```

**Comment by EloyAnguiano** [comment]
The previous code indeed creates a folder called `"rte_case5_example_00"` as it is my case, byt then I try to load that environment as `grid2op.make("rte_case5_example_00", test = True)` and it does not work. It returns: 

`grid2op.Exceptions.Grid2OpException.Grid2OpException: Grid2OpException "Impossible to load the environment named "rte_case5_example_00"."`

**Comment by EloyAnguiano** [comment]
Additionally, I try to build the environment with the same parameters as builded before like this:
```python
grid2op_env = grid2op.make(
                name=f"{env_grid2op.name}_{ch}",
                backend=env_grid2op.backend,
                test=env_grid2op.name == "rte_case5_example",
                action_class=env_grid2op._actionClass,
                reward_class=env_grid2op._rewardClass,
                param=env_grid2op.parameters,
            )
```
And this returns:
```
grid2op.Exceptions.Grid2OpException.Grid2OpException: Grid2OpException "Impossible to create an environment without its name. Please call something like: 
> env = grid2op.make('l2rpn_case14_sandbox') 
or
> env = grid2op.make('rte_case14_realistic')"
```

**Comment by BDonnot** [comment]
Try to run the script exactly as they appear. See if it works and then, only then , when you manage to reproduce it try to modify it.

For the first problem: I don't remember to have specified `test=True` and this is what cause the problem. Remember the warnings:
```
This environment is not intended for training agents.
```

So, whatever you publish, don't use it. And if you upgrade grid2op it will not work. If you really want to use this one, go to the location where grid2op is installed, locate the "data" folder and copy paste the `rte_case5_example` in the location where `grid2op.get_current_local_dir()` points to.

And then, just create it with `grid2op.make("rte_case5_example")` without `test=True`

So yes, please, DO NOT USE `test=True` if you do that.

**Comment by EloyAnguiano** [comment]
I am trying to use https://arxiv.org/abs/2310.02605 as a baseline, so I have to use the `rte_case5_example` environment.

**Comment by BDonnot** [comment]
You can use the `rte_case5_example` if you want, provided that you follow the steps above:
- locate the current directory that stores the environment
- copy paste it to the proper location
- call `make` without `test=True` 

Unfortunately, I can't spend any more time (as I already provided a working solution).

```python
grid2op_env = grid2op.make(
                name=f"{env_grid2op.name}_{ch}",
                backend=env_grid2op.backend,
                test=env_grid2op.name == "rte_case5_example",
                action_class=env_grid2op._actionClass,
                reward_class=env_grid2op._rewardClass,
                param=env_grid2op.parameters,
            )
```

Concerning this piece of code, there is pretty much nothing to keep... What will cause you tons of trouble is 

```
backend=env_grid2op.backend,
```

You should never do that (and grid2op will prevent you to do so !)

Instead do something like this:


```python
import grid2op
import os
import shutil
from lightsim2grid import LightSimBackend

def get_env_kwargs():
    return dict(test=False, backend=LightSimBackend(), action_class=..., reward_class=..., param=..., ...)

nb_env = 3
id_start = 17
env_name = "l2rpn_case14_sandbox"

# create the environment
env = grid2op.make(env_name, **get_env_kwargs())

# then later on
test_env = grid2op.make(env_name+"_"+ts_this, **get_env_kwargs())
```
