### ISSUE TITLE
Thermal limits in trafos

### ISSUE THREAD

**Issue by camiloromers** [rte-france/Grid2Op#6]
Please be aware when you modify the 'sn_mva'  you are altering the impedance of the element because (I am almost sure) pandapower uses this value to get the impedance in the t model and also treats as overloaded when the result of the power flow is above this value.

**Comment by BDonnot** [comment]
The PandaPowerBackend class does not change the "sn_mva" values of the transformers. 

What it means however is that we will need another files describing the thermal limit to use when loading the backend. This is a different issue though :-)
