### ISSUE TITLE
Switch problems for maintenance functions in the environment("l2rpn_wcci_2020")

### ISSUE THREAD

**Issue by King9299** [rte-france/Grid2Op#601]
Hello, we are using environment "l2rpn_wcci_2020" now. We want to turn off the maintenance function in environment "l2rpn_wcci_2020". May I ask how we should do it? 

I'd appreciate it if you could answer.

**Comment by BDonnot** [comment]
Hello,

It depends on how the environment is created. But if you did not change it too much you can do:

```python
import grid2op
from grid2op.Chronics import GridStateFromFileWithForecastsWithoutMaintenance
env = grid2op.make("l2rpn_wcci_2020",
                   data_feeding_kwargs={'gridvalueClass': GridStateFromFileWithForecastsWithoutMaintenance}
                  )
```

It will most likely work (I did not tested this code snippet so feel free to make sure there is no maintenance generated)

**Comment by BDonnot** [comment]
Any news on that ? (feel free to close the issue if it solves the issue. I'll close next week if no news)
