### ISSUE TITLE
Update Introduction.ipynb

### ISSUE THREAD

**Issue by DEUCE1957** [rte-france/Grid2Op#622]
## Documentation issue description
Looking at the 'gettting_started' / 'Introduction.ipynb' I see some interesting parameters (such as the ability to increase the no. of editable substations or powerlines in 1 action). 

However, under the Header 'Comparison with "the reality"' it still says we are limited to 2 busbars in Grid2Op:
"You can also have more than 2 busbars in each substation (sometimes 5 or 6 for example). This makes the number of possible topologies even higher than what it is in grid2op."

Could be changed to:
"You can also have more than 2 busbars in each substation (sometimes 5 or 6 for example). By default there are only 2 busbars per substation in Grid2Op, which corresponds to a lower number of possible topologies. However this can be changed when creating the environment by passing 'n_busbar=X' (where X is an integer) to grid2op.make"

**Comment by BDonnot** [comment]
Release made just now :-)
