### ISSUE TITLE
Downloading additional chronics

### ISSUE THREAD

**Issue by pwdemars** [rte-france/Grid2Op#63]
I am a little confused about how to download additional chronics. From the getting started notebook 0 (basic functionalities) it seems to suggest I can pass `local=False` to `make_new()` when creating the environment then it will download chronics, but this is not a valid keyword argument at the moment. 

I was familiar with the old approach to downloading chronics from the command line but now I don't know the URL for this download! (I am trying to download the extra chronics for rte_case14_realistic.) 

Incidentally, is there a preferred function out of `make()` `make2()` and `make_new()`?

**Comment by BDonnot** [comment]
Hello Patrick,

Thanks for this issue. I think we push a wrong version for the notebook. There are typo there. The key-word argument is "test" and not "local" sorry about that. We'll fix it in the next release.

The proper way to do it is then:
```python3
from grid2op import make_new  # this will become the new "make" in next release
env = make("l2rpn_case14_sandbox")
```
And that's it :-)
Note the first time you will use it, it will download approximately 300MB of data.
Afterwards it will automatically load this dataset without downloading it again.

And for clarification:
- the current `make` of 0.7.1 and earlier will be deprecated in v0.8.0 so i don't suggest you use it.
- the `make2` will become `make_from_dataset_path` in 0.8.0. Only use it if you know what you are doing.
- the `make_new` will become `make` and merges efficiently the creation and downloading of the environment (no need to use `grid2op.download` if you use the current `make_new`). It's the preferred way to create a valid environment.

 Best

Benjamin

**Comment by pwdemars** [comment]
Great, that works - thanks!
