### ISSUE TITLE
[FIXED] wrong layout for l2rpn_case14_sandbox..

### ISSUE THREAD

**Issue by BDonnot** [rte-france/Grid2Op#73]
The layout for the cas14 sandbox competition is wrong on some platform, but not on other.

```python
import grid2op
env = grid2op.make("l2rpn_case14_sandbox")
env.render()
```
And this is what i got:
![image](https://user-images.githubusercontent.com/9463182/81478424-a6e5b400-921d-11ea-8028-94014d03f7f0.png)

**EDIT** If the problem persists, remove the dataset from the cache and try to download it again. grid2op cache location is accessible through
```python
import grid2op
grid2op.get_current_local_dir()
```

**Comment by Tezirg** [comment]
All datasets were providing correct `grid_layout.json` files, except for `rte_case14_redisp`.

This has been updated: Removing datasets folders in `~/data_grid2op` will trigger download and update correctly. 
From clean cache all plotting is correct now.
