### ISSUE TITLE
Parrallel powerlines not displayed

### ISSUE THREAD

**Issue by BDonnot** [rte-france/Grid2Op#75]
The parrallel powelines are not displayed properly, the will overlap in the plot helper.

reproduce it:

```python3
import grid2op
env = grid2op.make("rte_case5_example", test=True)
obs = env.reset()
_ = env.render()
```
![image](https://user-images.githubusercontent.com/9463182/81536231-7dd33980-936b-11ea-9db1-bd1c9d15795f.png)

There are actually 2 powerlines going from substation 2 to substations 3

**Comment by Tezirg** [comment]
Fixed `PlotGrid` in 0.8.2
