### ISSUE TITLE
PlotGrid.PlotMatplot lisibility improvements

### ISSUE THREAD

**Issue by Tezirg** [rte-france/Grid2Op#94]
## Is your feature request related to a problem? 
For large grids with many loads/gen/lines and substations, the texts impair the lisibility of the plot.
Also, the GIF tend to "jump"

## Describe the solution you'd like
 - Add an option to disable the rendering of the text / part of the text in the `PlotMatplot` class
 - Use that flag by default in `EpisodeReplay`
 - Fix the 'jumping" bug

**Comment by BDonnot** [comment]
"jumping" bug is probably due to the usage of "tight_layout": if some values close to the "corner" of the screen change, their size change hence when the layout is computed we have the impression that everything is moving. Having larger margin in the plot could solve the issue.

**Comment by Tezirg** [comment]
Done in 0.9.2
